### ISSUE TITLE
How to modify the user agent?

### ISSUE THREAD

**Issue by almicol** [astropy/pyvo#107]

**Comment by almicol** [comment]
Oops, sorry, here the description:
I'm writing a python script to access the ESO archive using pyvo, I want the community to download and use it, but I also want to keep track of how much it is used; for that I want to modify the user agent, adding to it an ESO-specific token. Could you think of implementing this feature? That would be very nice. Thanks.

**Comment by olebole** [comment]
Not sure whether this is what you need:
```
import pyvo
pyvo.utils.http.session.headers['Authorization'] = \
        'Token 0b72ce6d309e128ad0a76c5993eb5eb8'
```
will add the described header.

**Comment by funbaker** [comment]
Thats the correct way, see https://github.com/pyvirtobs/pyvo/blob/master/pyvo/utils/http.py#L14

**Comment by cbanek** [comment]
Hi @almicol , just want to let you know that there's an open PR (#157) for adding auth support in formally to pyvo if you're interested in looking at it.  The global session is going to be taken out in favor of the new auth system in version 1.0, so this may break you (sorry about that).  Let me know if you have any feedback to make this transition as easy as possible and if the new system fulfills your needs.

If there's no more issues or code changes required here, let me know and I can close out this issue.
