### ISSUE TITLE
Strategy for implementing SIAv2 binding?

### ISSUE THREAD

**Issue by gpdf** [astropy/pyvo#108]
Has there been thought given to a strategy for implementing a PyVO-style binding to SIAv2 services?  The v2 specification is so different in its parameters and in the return data that it is essentially a different protocol, and it's relatively difficult to imagine supporting both versions in a single version of SIAResults or SIAService.

There are enough v2 services coming into existence that it may be interesting to start work on a PyVO binding, and I have been considering whether to start down that road as a contribution to the project, but I'd first like to know if there is already a road map for it in your minds.

It does seem like there is a small but useful intersection between SIAv1 and SIAv2 for which a common Python binding could be provided, which might be helpful to users.  However, it is also important to fully support the greater query power of SIAv2, as well as the ObsCore data model that is used for the results returned from SIAv2.

**Comment by msdemlei** [comment]
On Mon, Dec 10, 2018 at 11:35:36AM -0800, gpdf wrote:
> Has there been thought given to a strategy for implementing a
> PyVO-style binding to SIAv2 services?  The v2 specification is so

Not really, no.

> different in its parameters and in the return data that it is
> essentially a different protocol, and it's relatively difficult to
> imagine supporting both versions in a single version of SIAResults
> or SIAService.

Agreed.

> There are enough v2 services coming into existence that it may be
> interesting to start work on a PyVO binding, and I have been
> considering whether to start down that road as a contribution to
> the project, but I'd first like to know if there is already a road
> map for it in your minds.

That would certainly be great.  My take there would be that there
should be a general ObsCoreResult class that takes (reasonable
variations of) ObsCore rows, which would later let us have some nice
abstraction of obscore results, too ("GlobalObscoreService",
perhaps?).

The actual query interface ("SIA2Service") shouldn't be terribly
troublesome; you might want to look at the SODA interface
implementation for inspirations on how POS and friends might be
passed in (the two should be kept in sync, anyway).

> It does seem like there is a small but useful intersection between
> SIAv1 and SIAv2 for which a common Python binding could be
> provided, which might be helpful to users.  However, it is also

Hm... My take would be that we should be thinking about a common
discovery mechanism ("give me SIAv1 and SIAv2 services with the
following properties") and a common way to construct and query them;
but I suspect the right way to do this is going to be much more
obvious when we have the SIAv2 API.

Thanks,

          Markus

**Comment by funbaker** [comment]
It probably needs to be a separat SIA2Service class; the registry code needs to be adjusted as well, and there should be a exception when using the wrong service class.

**Comment by bsipocz** [comment]
I think this has been practically done now. There are still a few rough edges, but those have their own separate issues, so this big picture one can be closed.
