### ISSUE TITLE
Create and execute transition plan for future PyVO maintenance and development

### ISSUE THREAD

**Issue by RayPlante** [astropy/pyvo#127]
Prompted by in part by recent changes in project funding, folks from the IVOA and Astropy communities have been discussing how to ensure further community-based support for PyVO going forward. In particular, @timj noted in PR #119, 

> Not knowing where else to mention this, but last week at IVOA @msdemlei, @cbanek, representatives from ESAC, and CADC, and Astroquery developers discussed the future of pyvo and we came up with a plan of moving pyvo to the Astropy org and changing Astroquery so that it depends on pyvo. @RayPlante was also kept in the loop.

This Issue can provide a thread for further discussion of such a plan (particularly the part about "moving pyvo to the Astropy org").  

My personal thanks go to all the submitters over the last few years, those involved in the IVOA discussion, but especially to Stefan (@funbaker) and Markus (@msdemlei) for their injection of care and effort into this project as I switched my attention to other projects.

**Comment by RayPlante** [comment]
Meant also to tag @eteq.

**Comment by cbanek** [comment]
I also just want to chime in with my thanks for all the work keeping this running, and am happy that I'll be able to spend a bit more time with helping on pyvo!  I mostly just hope to fix bugs and keep adding extensions in pyvo to make it keep working with VO services that we'll be using.  Of course having a great generic client helps everyone, and I'm happy to be a part of it.

**Comment by funbaker** [comment]
I cannot actively develope, but i'd be happy to function as a reviewer when my time permits.

**Comment by pllim** [comment]
Would probably be nice to have a formal `ROADMAP.md` file (or RST, whatever your fav format is) in the root level of the repo to lay out this plan. It can just contain high level goals, split into some reasonable time frame when you want them accomplished. For example:

* In the next release, we plan to ...
* In the next year, we plan to ...
* Longer term, we plan to ...

**Comment by funbaker** [comment]
> Would probably be nice to have a formal `ROADMAP.md` file

Why not the github feature, like in the astropy project itself?

**Comment by pllim** [comment]
I guess GitHub project board works too. But with ROADMAP, you can version control it along with all the other files in the repo. Not sure how you can version control project board. Anyways, pick your poison. 😉

**Comment by funbaker** [comment]
Looks like I am missing the permissions to review and setup the project board...

**Comment by RayPlante** [comment]
It looks like the move to the astropy org happened promptly a week ago; thus, the change in available permissions.  The carpet and the wallpaper are the same, so I didn't notice.  Welcome, everybody!

**Comment by funbaker** [comment]
Excuse me for being a bit off-topic here, but i would appreciate being in the pyvo-maintainer group.

**Comment by eteq** [comment]
@funbaker - yep, that makes sense! I will add you (since I'm an org admin), and I've sent an email with further information.  Let me know if you don't get it (and send me an email to use if it doesn't come through).

**Comment by cbanek** [comment]
So I think for now, since we don't have a lot of issues created we should just use that for the roadmap.  I've been tagging things with various releases, and this way if someone clicks on the release they can see all the things we hope to do in that release, which is I think good enough for us for now.  Plus this way there's no way for the plan to get out of sync with the tickets this way, which is helpful for forgetful me.

**Comment by cbanek** [comment]
As we are definitely executing on this, I'm going to close this out.  Feel free to make issues to add them to the plan, and we've got the milestones which the astropy bots are watching too.
