### ISSUE TITLE
TST: Tests broke with pedantic=True not raising error

### ISSUE THREAD

**Issue by pllim** [astropy/pyvo#130]
I think this is caused by astropy/astropy#8715 by @astrofrog .

Example log: https://travis-ci.org/astropy/pyvo/jobs/537161894

```
__________________________ TestTables.test_no_schemas __________________________
self = <pyvo.io.vosi.tests.test_tables.TestTables object at 0x7fcca5c29400>
    def test_no_schemas(self):
        with pytest.warns(W14):
            vosi.parse_tables(
                get_pkg_data_filename("data/tables/no_schemas.xml"))
    
        with pytest.raises(W14):
            vosi.parse_tables(
                get_pkg_data_filename("data/tables/no_schemas.xml"),
>               pedantic=True)
E           Failed: DID NOT RAISE <class 'pyvo.io.vosi.exceptions.W14'>
pyvo/io/vosi/tests/test_tables.py:121: Failed
__________________ TestTables.test_multiple_column_datatypes ___________________
self = <pyvo.io.vosi.tests.test_tables.TestTables object at 0x7fcca5b514a8>
    def test_multiple_column_datatypes(self):
        with pytest.warns(W37):
            vosi.parse_tables(get_pkg_data_filename(
                "data/tables/multiple_column_datatypes.xml"))
    
        with pytest.raises(W37):
            vosi.parse_tables(
                get_pkg_data_filename(
                    "data/tables/multiple_column_datatypes.xml"),
>               pedantic=True)
E           Failed: DID NOT RAISE <class 'pyvo.io.vosi.exceptions.W37'>
pyvo/io/vosi/tests/test_tables.py:283: Failed
___________________________ TestTables.test_tap_size ___________________________
self = <pyvo.io.vosi.tests.test_tables.TestTables object at 0x7fcca54680b8>
    def test_tap_size(self):
        with pytest.warns(W03):
            vosi.parse_tables(get_pkg_data_filename(
                "data/tables/sizenegative.xml"))
    
        with pytest.raises(W03):
            vosi.parse_tables(get_pkg_data_filename(
                "data/tables/sizenegative.xml"),
>               pedantic=True)
E           Failed: DID NOT RAISE <class 'pyvo.io.vosi.exceptions.W03'>
pyvo/io/vosi/tests/test_tables.py:293: Failed
```

**Comment by pllim** [comment]
The offending warning codes seem to have something in common, in that they do not inherit from `VOTableSpecWarning`:

https://github.com/astropy/astropy/blob/1658b5ac0a5ecf3b84ce284a5629fd9cabbd6c43/astropy/io/votable/exceptions.py#L540 -- Wut?!!

```python
# W14: Deprecated
```

https://github.com/astropy/astropy/blob/1658b5ac0a5ecf3b84ce284a5629fd9cabbd6c43/astropy/io/votable/exceptions.py#L848

```python
class W37(UnimplementedWarning)
```

https://github.com/astropy/astropy/blob/1658b5ac0a5ecf3b84ce284a5629fd9cabbd6c43/astropy/io/votable/exceptions.py#L304

```python
class W03(VOTableChangeWarning)
```

**Comment by pllim** [comment]
pllim [5:40 PM]
I tried to code dive but I got very lost. I followed

https://github.com/astropy/pyvo/blob/5a38ee732587c505b4dbaaed4dfce9daffccfce3/pyvo/io/vosi/endpoint.py#L251

to

https://github.com/astropy/pyvo/blob/5a38ee732587c505b4dbaaed4dfce9daffccfce3/pyvo/utils/xml/elements.py#L266

and then not sure how that maps back to `astropy.io.votable`.

**Comment by pllim** [comment]
But stepping back from the rabbit hole... I think I know why this is happening. Over at `astropy`, we switched from `pedantic` to `verify` at a very high level

https://github.com/astropy/astropy/blob/1658b5ac0a5ecf3b84ce284a5629fd9cabbd6c43/astropy/io/votable/table.py#L29

and 

https://github.com/astropy/astropy/blob/1658b5ac0a5ecf3b84ce284a5629fd9cabbd6c43/astropy/io/votable/table.py#L133-L144

and then from then on, we check against `config['verify']` only and pretend `config['pedantic']` isn't a thing anymore:

https://github.com/astropy/astropy/blob/1658b5ac0a5ecf3b84ce284a5629fd9cabbd6c43/astropy/io/votable/converters.py#L442

Meanwhile, PyVO seems to pass `config['pedantic']` around at a very low level. So I think the solution is for PyVO to do a version check for `astropy>=4`, which if `True`, you need to pass around `verify` instead. And keep in mind that `verify` takes string, not `bool`, as described in astropy/astropy#8715

**Comment by funbaker** [comment]
VOTable? This is a XML Parser based on astropy, but it is parsing VOSI http://www.ivoa.net/documents/VOSI/20170524/REC-VOSI-1.1.html

**Comment by funbaker** [comment]
For later consideration: There are also those replicated methods here: https://github.com/astropy/pyvo/blob/master/pyvo/utils/xml/exceptions.py#L25

(For some reason i created them but didnt used them in the xml parser)
