### ISSUE TITLE
MNT: Remove duplicate code in pyvo.utils.xml.exceptions

### ISSUE THREAD

**Issue by pllim** [astropy/pyvo#141]
As brought up by @funbaker in https://github.com/astropy/pyvo/issues/130#issuecomment-498203485

*For later consideration: There are also those replicated methods here:*

https://github.com/astropy/pyvo/blob/3cb3434abc9ffb6559a323edef6e4d0783cca38a/pyvo/utils/xml/exceptions.py#L25

*(For some reason i created them but didnt used them in the xml parser)*

**Comment by cbanek** [comment]
Actually this was used in a different place, but in #140 I've made them all use the astropy version.  I'll put out this part in a later PR.

It seems like the UnknownElement is referenced in the code base (and therefore its base class, and _format_message), but the other functions and UnknownAttributeWarning are unused?  I'm just grepping around, so I may be missing something.

**Comment by funbaker** [comment]
I think the reason for this stub is because it was hard to determine if an attribute is unknown.

The right place to put such a check would be in https://github.com/astropy/pyvo/blob/master/pyvo/utils/xml/elements.py#L261

**Comment by cbanek** [comment]
Looks like Tim's new flake8 checking found an unused import now that I rebased on top of that, rebuilding.
