### ISSUE TITLE
Move top level tests directory to relevant location

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#144]

**Comment by bsipocz** [comment]
`examples` may also be worked into the narrative docs and moved to `docs`.

**Comment by cbanek** [comment]
Yeah that tests/ folder with the testLicense.py does look a little out of place.  I guess we could move that into the normal testing regime, I'm not sure why we couldn't run this as a part of the tests, although it does also feel strange.  I don't really know where this belongs, any thoughts?

**Comment by bsipocz** [comment]
no firm  ideas, would have said otherwise 😅
