### ISSUE TITLE
List jobs functionality missing in TAP

### ISSUE THREAD

**Issue by andamian** [astropy/pyvo#150]
Users need a way to list their own TAP jobs. This will only work when auth is supported (#122)

**Comment by cbanek** [comment]
And there is a UWS standard way of listing the jobs, so it's not like we have to invent the way to do it, we just need to implement the client part of it.

**Comment by funbaker** [comment]
Job are already getting parsed, it *should* work if auth is mixed in.

**Comment by funbaker** [comment]
I guess it's more complicated than that. The `jobref` element is missing as well, and it has to be resolved as well.

I'd stick to the scheme of putting the top-level parsing function into `pyvo.io.uws.endpoint` and the pure element classes into `pyvo.io.uws.tree`.

For resolving references i'd do something similar to `pyvo.dal.vosi.VOSITables`
