### ISSUE TITLE
Move astroquery.vo_conesearch to pyvo?

### ISSUE THREAD

**Issue by pllim** [astropy/pyvo#154]
I am not excited to have to move it *again* but I vaguely remember this topic was brought up at IVOA Interop but I don't remember the conclusion. cc @tomdonaldson

**Comment by funbaker** [comment]
Conesearch is already implemented, so this would be redundant (if not missing something).

**Comment by pllim** [comment]
Yeah, I dunno. Maybe it should just stay in `astroquery` for convenience.... @keflavich and @bsipocz , do you remember if we talked about this?

**Comment by keflavich** [comment]
astroquery is a reasonable place for frontendy things (user-facing things) to live, so I'm ok with that.

**Comment by pllim** [comment]
OK, let's keep life simple then. Thanks for the feedback!
