### ISSUE TITLE
 Use key 'uploads' in search() encontered Error 

### ISSUE THREAD

**Issue by qu123xxx** [astropy/pyvo#161]
When I  use `search()` to upload a'votable' named mag to query Simbad, an error happened.

```
service.search("SELECT mag.MAIN_ID,allfluxes.B,V\
... FROM TAP_UPLOAD.query LEFT OUTER JOIN ident ON ident.id = mag.MAIN_ID\
... LEFT OUTER JOIN allfluxes ON allfluxes.oidref=ident.oidref",uploads='mag')
```
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Program Files\Python37\lib\site-packages\pyvo\dal\tap.py", line 194, in run_sync
    **keywords).execute()
  File "C:\Program Files\Python37\lib\site-packages\pyvo\dal\tap.py", line 302, in create_query
    self.baseurl, query, mode, language, maxrec, uploads, **keywords)
  File "C:\Program Files\Python37\lib\site-packages\pyvo\dal\tap.py", line 760, in __init__
    self._uploads = UploadList.fromdict(uploads or {})
  File "C:\Program Files\Python37\lib\site-packages\pyvo\dal\query.py", line 1038, in fromdict
    return cls(Upload(key, value) for key, value in dct.items())
AttributeError: 'str' object has no attribute 'items'
```

Return: `AttributeError: 'str' object has no attribute 'items'`

The VoTable is write from table.write('mag',format='votable').The table's detail is show in picture.

![image](https://user-images.githubusercontent.com/16397369/61821378-a5fbb580-ae89-11e9-864f-1ecd7f7dd654.png)

**I have tried the same file and  ADQL code at the Simbad: TAP Service,and it worked.**
 http://simbad.u-strasbg.fr/simbad/tap/help/adqlHelp.html

**I want to ask how to upload files in correct way to query the data?**

The Votable file mentioned abvove: [mag.zip](https://github.com/astropy/pyvo/files/3428281/mag.zip)

**Comment by cbanek** [comment]
Thanks for reporting this!  I don't know what is going on, but thanks for uploading the table.  I'll try to reproduce this and let you know if it works for me or not.

**Comment by qu123xxx** [comment]
You can follow this process to reproduce it.
`mag=astropy.table.Table.read('mag')`
`service = vo.dal.TAPService("http://simbad.u-strasbg.fr/simbad/sim-tap")`
```
service.search("SELECT mag.MAIN_ID,allfluxes.B,V \
        FROM TAP_UPLOAD.mag LEFT OUTER JOIN ident ON ident.id = mag.MAIN_ID \
        LEFT OUTER JOIN allfluxes ON allfluxes.oidref=ident.oidref",uploads='mag')
```
You can also upload the file to here :http://simbad.u-strasbg.fr/simbad/sim-tap and name it mag then type  :
```
SELECT mag.MAIN_ID,allfluxes.B,V
        FROM TAP_UPLOAD.mag LEFT OUTER JOIN ident ON ident.id = mag.MAIN_ID
        LEFT OUTER JOIN allfluxes ON allfluxes.oidref=ident.oidref
```
into the query box and click START, you will see a new window with result in it . That means the file can worked in SIMBAD's official TAP Service client.

**Comment by cbanek** [comment]
Okay, so I think I've found the issue.

Right now you're passing uploads='mag', which is a string with the value mag.  It's not mag, the python variable.  But when I tried that, I got a more different error.  Then I looked at the docstring to help me debug, and it said:

    uploads : dict
        a mapping from table names to file like objects containing a votable

I've gotten it to work in this following example:

```
import astropy.table
import pyvo

mag = astropy.table.Table.read('mag')
upload_dict = {'mag': mag}

service = pyvo.dal.TAPService("http://simbad.u-strasbg.fr/simbad/sim-tap")
results = service.search("SELECT mag.MAIN_ID,allfluxes.B,V \
        FROM TAP_UPLOAD.mag LEFT OUTER JOIN ident ON ident.id = mag.MAIN_ID \
        LEFT OUTER JOIN allfluxes ON allfluxes.oidref=ident.oidref",uploads=upload_dict)

print(results)
```

Which prints out:

```
WARNING: W50: None:16:3: W50: Invalid unit string '"h:m:s"' [astropy.io.votable.tree]
WARNING: W50: None:21:3: W50: Invalid unit string '"d:m:s"' [astropy.io.votable.tree]
WARNING: W50: ?:?:?: W50: Invalid unit string '"h:m:s"' [astropy.io.votable.tree]
WARNING: W50: ?:?:?: W50: Invalid unit string '"d:m:s"' [astropy.io.votable.tree]
<Table masked=True length=4>
       MAIN_ID                B                 V        
        object             float64           float64     
--------------------- ----------------- -----------------
            *  81 Vir                --                --
          *  81 Vir A   8.6899995803833 7.679999828338623
          *  81 Vir B 8.960000038146973  7.96999979019165
1RXS J133734.6-075257 
```

**Comment by qu123xxx** [comment]
Thanks for your reply. I haven't realized I should use a Mapping Types——dict instead of using the  string 'mag'. That caused the error.:dizzy_face:

**Comment by funbaker** [comment]
Feel free to submit a pull request to optimize the documentation :)
