### ISSUE TITLE
Allow searching for multiple wavebands in registry.regsearch()

### ISSUE THREAD

**Issue by cbanek** [astropy/pyvo#176]
In #175 we fixed a bug with searching for wavebands, and @msdemlei had the idea of being able to search for multiple wavebands too, which sounds like a good one.  Just noting that as a separate feature so we can close out the bug and keep track of this in the future.

**Comment by msdemlei** [comment]
With #289, you can create a Waveband constraint with multiple arguments, which will do what's proposed here.
