### ISSUE TITLE
Simplify the release process

### ISSUE THREAD

**Issue by andamian** [astropy/pyvo#181]
Trigger with tagging in github and execute in Travis after running all the tests.

**Comment by andamian** [comment]
What I have in mind here is to release `pyvo` with a `Travis` job when a release is created in `github`. I've done that and I know it works for publishing to `pypi` but I'm not sure what the process entails for releasing it to `conda`. @funbaker, @cbanek or anyone else has a better suggestion or should I attempt a first PR to stir the discussion?

**Comment by funbaker** [comment]
For conda it also creates a PR automatically on https://github.com/conda-forge/pyvo-feedstock but i got no idea how exactly, and someone needs to submit the PR.

**Comment by bsipocz** [comment]
A lot has been simplified, and https://github.com/astropy/pyvo/issues/247 is tracking the one remaining option for further automatisation.
