### ISSUE TITLE
Possible documentation error in DALQuery docstrings?

### ISSUE THREAD

**Issue by gpdf** [astropy/pyvo#182]
https://github.com/astropy/pyvo/blob/bf2c854fa98ddf1e3883e8c3e7aae996215d7008/pyvo/dal/query.py#L219

indicates that DALQuery.execute_votable() returns "astropy.io.votable.tree.Table", but it appears that it actually returns "astropy.io.votable.tree.VOTableFile" which has a different interface.

**Comment by cbanek** [comment]
I can certainly believe it, probably just the docs are wrong.  We've got a couple of these documentation issues I'll try to roll into a PR in the next couple of weeks
