### ISSUE TITLE
Handle UWS XML ISO+RFC-822 offset date formats

### ISSUE THREAD

**Issue by jcsegovia** [astropy/pyvo#184]
PyVo is expecting ‘iso’ or ‘isot’ formats.

A widely used format is ISO with RFC-822 offsets.

```
PyVo 'isot' UTC/Zulu: 2009-05-19T13:01:44.038Z
iso+RFC-822: 2009-05-19T15:01:44.038+0200
```

I think ISO+RFC-822 should be accepted.

**Comment by msdemlei** [comment]
On Thu, Oct 17, 2019 at 05:29:33AM -0700, jcsegovia wrote:
> 
> ```
> PyVo 'isot' UTC/Zulu: 2009-05-19T13:01:44.038Z
> iso+RFC-822: 2009-05-19T15:01:44.038+0200
> ```
> 
> I think ISO+RFC-822 should be accepted.

Uh, no, on this I strongly disagree.  All recent VO standards agree
that time zones are not allowed, as codified in DALI:
http://ivoa.net/documents/DALI/20170517/REC-DALI-1.1.html#tth_sEc3.3.3

Services that include time zones are hence (for all sane standards)
in violation of the spec and need to be fixed.  Working around buggy
services on the client side just leads down a road of pain where
certain services happen to work with just a few clients (the ones the
operators happen to have tested) and suddenly fail with others.
We've been to far down that road already (and don't get me started on
the wider computing world -- ACPI.  Nuff said).

If you find a service that uses time zones and is flagged as valid by
the corresponding validator(s), would you alert the IVOA Ops WG?

           -- Markus

**Comment by cbanek** [comment]
I believe @msdemlei is correct on this one, I just looked through the UWS spec both 1.0 and 1.1, and they both say the following about timezones in section 2.2.1:

The string representation of instants of time follow [std:iso8601] with the following additional
constraints;
1. A character 'T' must be used to separate the date and the time.
2. Times must be expressed in the UTC timezone, and this is signified with the 'Z' timezone
designator.

**Comment by jcsegovia** [comment]
If UWS specifies no time zones allowed, I think we can close this issue.

(@andamian this ticket is asking for supporting RFC-822: time offset)
