### ISSUE TITLE
Handle missing UWS XML 'version' attribute

### ISSUE THREAD

**Issue by jcsegovia** [astropy/pyvo#185]
PyVo is expecting 'version' attribute and fails when it is not found. As this attribute is optional, the parser should be able to work without it:

UWS 1.1 (http://www.ivoa.net/documents/UWS/20161024/REC-UWS-1.1-20161024.html#versioning)

> Note that although this version attribute is marked as "**optional**" in the schema (for maintaining formal backwards compatibility), a UWS 1.1 compliant server must set the attribute value to "1.1"

**Comment by cbanek** [comment]
Fixed by #199
