### ISSUE TITLE
Handle 'format' TAP parameter

### ISSUE THREAD

**Issue by jcsegovia** [astropy/pyvo#186]
TAP specification allows the user to request results in a specific format.

'format' ('response_format' in v1.1) parameter is ignored and PyVo always tries to parse the results to convert them into a VOTable.

It would be useful to avoid translations of results in memory (performance issue: it is not optimal if we have to retrieve the results in VOTable and translate them into the requested format in memory).

**Comment by andamian** [comment]
duplicate of #149

**Comment by jcsegovia** [comment]
Yes. 'format' and 'responseformat' are already requested in #149 
I think we can close this issue.
