### ISSUE TITLE
Nightly travis build for pyvo

### ISSUE THREAD

**Issue by cbanek** [astropy/pyvo#208]
Since we don't build very often, it'd be nice to know when astropy helpers or other things change and we need to fix something.  So nightly would be nice to know when it changes to help debugging.

**Comment by bsipocz** [comment]
I would say a weekly is enough. 

E.g. we already have the cron travis job, that's a start to pick up these issues, assuming that the test suite is as complete as possible.

**Comment by cbanek** [comment]
Sure weekly sounds fine, anything recurring is good

**Comment by bsipocz** [comment]
Weekly cron is enabled. Currently the astrop dev job, and the osx one is running. Particularities can be modified with the .travis.yml file.
