### ISSUE TITLE
Docs: in user guide, show how to select RegistryResult records

### ISSUE THREAD

**Issue by stargaser** [astropy/pyvo#211]
A registry search frequently returns several records and the user must downselect these further to find their desired service. The NAVO group settled on list comprehensions for its January 2020 AAS workshop. The user guide could show how to select records based on `short_name` or `ivoid`.

Example:
```
import pyvo as vo
services = vo.regsearch(servicetype='conesearch', keywords=['swift'])
stsci_services = [s for s in services if 'stsci.edu' in s.ivoid]
for s in stsci_services:
    print (f'(STScI): {s.short_name} - {s.res_title}')
```

**Comment by trjaffe** [comment]
I'd like to see the list of these available attributes documented here as well.

**Comment by funbaker** [comment]
Well, feel free to submit a PR :)

**Comment by stargaser** [comment]
Yes! I plan to submit a documentation PR for this issue. I wanted to make the issue first so that I don't forget to do it.

**Comment by bsipocz** [comment]
The registry documentation got a big overhaul, so I would say this issue is now addressed.

However, I think it's wrong to do this via `vo.regsearch`, and we should instead consider deprecating that API endpoint in favour of  `vo.registry.search`.

**Comment by msdemlei** [comment]
On Tue, Jan 24, 2023 at 12:25:05PM -0800, Brigitta Sipőcz wrote:
> The registry documentation got a big overhaul, so I would say this issue is now addressed.
> 
> However, I think it's wrong to do this via `vo.regsearch`, and we should instead consider deprecating that API endpoint in favour of  `vo.registry.search`.

I'm ok with that – but have to admit I don't care enough to write up a
PR and hunt down all usage of regsearch.  Since I suspect there's
quite a bit of code out there using regsearch, we at least should not
rush its removal.
