### ISSUE TITLE
dal.vosi: Drop AvailabilityMixin

### ISSUE THREAD

**Issue by msdemlei** [astropy/pyvo#214]
I'd suggest we entirely drop AvailabilityMixin.  

For all I know, nobody so far has found a use for it, and it's
clear it doesn't work as planned, because its URI needs to be
per-access-URL (see Caproles, http://ivoa.net/documents/caproles/).

Also, of course, putting availability as a sibling to the service to be
checked makes it rather questionable anyway -- often, the machinery
supposed to serve availability will be down if the service under
investigation is down.

Given that, I'd say we should drop it before someone finds some twisted
use for it in some fringe use case and removing it actually hurts.

**Comment by bsipocz** [comment]
Some time has passed on this as the class is still around, so I would say this should be now a class deprecation or closing this issue without action. I milestone it for the next release so we don't forget about it.

**Comment by andamian** [comment]
Agree
