### ISSUE TITLE
job.wait hangs with Authorization token

### ISSUE THREAD

**Issue by agy-why** [astropy/pyvo#229]
## Context

I am working on the TAP service at gaia.aip.de ('https://gaia.aip.de/tap') and we are building simple examples for the users. While designing a minimal example I faced the following issue: running this script with pyvo 0.9.3.

```python
tap_service = vo.dal.TAPService(url)

tap_session = requests.Session()
tap_session.headers['Authorization'] = token
tap_service.session = tap_session

job = tap_service.submit_job(sql, language='postgresql', runid='batch1')

job.run()
print('Waiting for the job to finish...')
job.wait(phases=["COMPLETED", "ERROR", "ABORTED"], timeout=10.)
job.raise_if_error()

print('fetching results:')
results = job.fetch_result()

print('Done')
```

with sql being a valid request and token being a valid token. 

## Problem

This script will be executed on server side and is marked as COMPLETED but it will hang in the `job.wait()` method on client side.

Removing `tap_session.headers['Authorization'] = token` and running the same script as anonymous_user works smoothly. 

## What I expect

I expect that this script should not hang in the `job.wait()` method even with a token.

**Comment by cbanek** [comment]
Thanks for the report.  I would suggest trying a newer version of pyvo as we've added better auth support to it.  0.9.3 is pretty old.  Here's an example of how I do tokens for LSST: https://github.com/lsst-sqre/jupyterlabutils/blob/2c3c0aa4733d5e71af2b6e9c365a811cda675288/jupyterlabutils/notebook/catalog.py#L57

**Comment by agy-why** [comment]
Dear Christine, thank you for your fast answer. Indeed with pyvo 1.0.0 everything works fine. Thank you.
