### ISSUE TITLE
datalink: bysemantics should by default include the entire branch

### ISSUE THREAD

**Issue by msdemlei** [astropy/pyvo#231]
In case you're not aware of datalink in pyVO: there's examples in http://docs.g-vo.org/pyvo/html/page026.html.

In datalink, rows have an associated semantics; the terms there come from the controlled, hierarchical vocabulary at http://www.g-vo.org/rdf/datalink/core.  As you can see, there is structure in there; for instance, bias is a child of computation.

Now, I would like get bysemantics method of datalink results to take into account this structure by including, by default, all narrower terms, too.  I'd like to put this is before any real code depends on the current, IMHO less desirable behaviour.  I'd volunteer to implement that, but I'd be grateful for a piece of advice (below).

Consider, as a (non-ideal) example, http://dc.g-vo.org/kapteyn/q/dl/dlmeta?ID=ivo%3A//org.gavo.dc/~%3Fkapteyn/data/fits/POT015_000317.fits.  As you can see, this has two sorts of previews (the details don't really matter).  Now, if you run:

```
from pyvo.dal import adhoc

links = adhoc.DatalinkQuery(
9"http://dc.g-vo.org/kapteyn/q/dl/dlmeta",
9id="ivo://org.gavo.dc/~?kapteyn/data/fits/POT015_000317.fits").execute()
print(list(links.bysemantics("#preview-image")))
print(list(links.bysemantics("#preview")))
```

you will see that the second list (for the wider term) does not include
the first list, although of course everything in the first list "is-a"
preview by the semantics.  I would like to fix this; the second list
should include the first.

Concretely, I'm proposing that the bysemantics method of `dal.adhoc.DatalinkResults` should grow a keyword parameter `exact`, defaulting to `False`; and if `exact` is false, all terms narrower than the first argument should be included in the filter (there's a bit of legalese that needs to restrict this to terms in the IVOA vocabulary and such, but that's minor details).

Given recent developments in IVOA semantics, that's rather simple to
accomplish: You pull a file like
http://www.ivoa.net/rdf/datalink/core/2020-02-12/datalink.desise,
json-decode it and pull out the narrower terms for what you already
have (details on
http://ivoa.net/documents/Vocabularies/20200612/WD-Vocabularies-2.0-20200612.html#tth_sEc3).

The one trick: You don't want to pull that file every time you do a query.  It's essentially a slow-changing resource that we can safely cache for months (or perhaps only update on request).  I suspect pyvo or astropy has similar problems in other places -- is there perhaps already a solution for this kind of thing?

And: Do people find this idea particularly disgusting?

[oh: if you think we ought to have `exact=True` by default... well, yes, that would alleviate qualms with possible backward compatibility, but it'd make the less expectable functionality the default, which I usually try to avoid...]

**Comment by funbaker** [comment]
Astropy has indeed a cache functionallity - see https://docs.astropy.org/en/stable/utils/data.html
