### ISSUE TITLE
Move CI to GH Actions

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#244]
As travis has ceased to support open source, the travis part of the CI has stopped for all repos in the astropy org. Some packages got moved over already, their configs could be used as guidence (e.g. pytest plugins, photutils, core).

Longer description is in this astropy-dev mail: https://groups.google.com/g/astropy-dev/c/45frnTEAX-U

Their announcement: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by andamian** [comment]
@bsipocz , @pllim - do you have any examples of repos that have made the transition? I'd like as much as possible to keep a consistent style in naming and actions. Also, do you know whether the `pypi` password is available from the `satrapy` organization? I am not a `github` admin on this project so I'd probably need to work with one to make sure `actions` are enabled and the `master` branch is protected accordingly.

**Comment by pllim** [comment]
Actions is automatically enabled when the YAML is in the branch. For the first time when it is in your PR but not upstream, you can check the Actions tab on your fork.

As for protecting the branch, seems like I am able to do it, but let's wait for the new CI to be working first before we do that.

Hope this helps!

> examples of repos

Yes, `astropy` transitioned, as well as some coordinated packages, such as `photutils`.

> `pypi` password

Not sure. What do you need it for? @astrofrog and @cadair got something going in `astropy` that interacts with PyPI but it runs on Azure Pipelines.

**Comment by andamian** [comment]
Thanks @pllim - that helps!

`pypi` password is to be able to automatically publish with GitHub Actions when a new release is created in Github. Password can be set at the organization level and explicitly made available to individual repos. I can provide more details if required.

**Comment by pllim** [comment]
For auto PyPI publication, I'll have to defer to @astrofrog and @Cadair .

**Comment by bsipocz** [comment]
@andamian - I also have to figure this out for astroquery, but have very little time, so might be ditch continuous delivery for the short run.

**Comment by bsipocz** [comment]
Maybe this thread (more tips in later emails) would be the first place I would start looking for recipes for this: https://mail.python.org/pipermail/numpy-discussion/2020-November/081206.html

**Comment by andamian** [comment]
An initial version has been merged into master. Following will track a few outstanding related issues to be included into a subsequent PR:
- update the build badge
- currently, the main matrix runs on `astropy` (3.7, 3.8, 3.9 and latest) and os (linux, windows and Mac). Add 4.0, 4.1 and 4.2 and run windows and Mac only with latest astropy.
- `pypi` publish task (TBD)
- others?

**Comment by pllim** [comment]
Thank you very much! Feel free to close this issue when you think it can be closed. 😄

**Comment by andamian** [comment]
Publishing part is tracked under #247 . Closing this one now.
