### ISSUE TITLE
TAPService describe() fails parsing the /capabilities

### ISSUE THREAD

**Issue by almicol** [astropy/pyvo#257]
The following tap.describe() call:
```
import pyvo as vo
from pkg_resources import parse_version

if parse_version(vo.__version__) < parse_version('1.0'):
    raise ImportError('pyvo version must be 1.0 or higher')
    
print('\npyvo version {version} \n'.format(version=vo.__version__))

SPECIAL_TAP = "http://dfidev5.hq.eso.org:8123/tap"
tap = vo.dal.TAPService(SPECIAL_TAP)
tap.describe()
```

returns:
```
pyvo version 1.1 

WARNING: UnknownElementWarning: None:1:580: UnknownElementWarning: Unknown element dataModel [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:659: UnknownElementWarning: Unknown element language [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:669: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:686: UnknownElementWarning: Unknown element version [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:781: UnknownElementWarning: Unknown element languageFeatures [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:852: UnknownElementWarning: Unknown element feature [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:861: UnknownElementWarning: Unknown element form [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:889: UnknownElementWarning: Unknown element feature [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:898: UnknownElementWarning: Unknown element form [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:927: UnknownElementWarning: Unknown element feature [pyvo.utils.xml.elements]
Capability ivo://ivoa.net/std/TAP

ADQL-2.0

Interface ns5:ParamHTTP
    http://dfidev5.hq.eso.org:8123/tap


Capability ivo://ivoa.net/std/DALI#examples

Interface ns4:WebBrowser
    http://dfidev5.hq.eso.org:8123/tap/examples

```

Also, the call:
```
print(tap.hardlimit)
```
gives a: raise DALServiceError("Hard limit not exposed by the service")
despite it being well defined in the /capabilities.

The full /capabilities of that service can be found [here](http://www.locimicol.eu/work/devdfi5_capabilities.xml)
(given that the development server is behind our firewall).

taplint on that tap service does not return any error.

I would be very grateful if you could check the above. 
Is it a problem in our XML, or is a pyvo issue?
My hint: Could it be that the used namespaces are not recognised by pyvo?

Many thanks in advance,
Alberto

**Comment by msdemlei** [comment]
On Wed, Mar 31, 2021 at 09:11:49AM -0700, almicol wrote:
> SPECIAL_TAP = "http://dfidev5.hq.eso.org:8123/tap"
> 
> WARNING: UnknownElementWarning: None:1:580: UnknownElementWarning: Unknown element dataModel [pyvo.utils.xml.elements]

This looks like something is wrong with your capabilities response --
but http://dfidev5.hq.eso.org:8123/tap/capabilities times out for me.

If you can make that accessible from the outside or just e-mail the XML
to me, I'm quite sure I can help you.

**Comment by almicol** [comment]
Thanks for looking into it! 
As already mentioned in the ticket, the /capabilities xml can be found here: http://www.locimicol.eu/work/devdfi5_capabilities.xml

**Comment by almicol** [comment]
BTW, this new TAP we are developing is TAP v1.1, is pyvo supporting it?

**Comment by msdemlei** [comment]
On Thu, Apr 01, 2021 at 12:50:46AM -0700, almicol wrote:
> Thanks for looking into it! 
> As already mentioned in the ticket, the /capabilities xml can be found here: http://www.locimicol.eu/work/devdfi5_capabilities.xml

Oh, sorry, I hadn't looked for anything below the machine
gobbledigook.  And your hunch is almost right: It's not the
namespaces, it's the prefixes you map them to.  You see, XML schema
blew up the (reasonably) nice XML namespacing spec by taking
namespaced (more precisely: QName-d) attribute *values* from XSLT.
This means that non-schema aware parsers (like the one pyvo uses) or
parsers without access to the schema have no way of knowing that they
would need to turn your ns4:TableAccess in xsi:type to
{http://www.ivoa.net/xml/TAPRegExt/v1.0}TableAccess (in conventional
notation).

To save people's nerves (to some extent), the VO's registry
ecosystem introduced the notion of canonical prefixes that, depending
on the context must or should be used; a relatively current list of
these canonical prefixes is in RegTAP,
https://ivoa.net/documents/RegTAP/20191011/REC-RegTAP-1.1.html#tth_sEc5
(which also reviews the problem from an ADQL query aspect).

Now, while VOSI, I think, does not prescribe the use of the canonical
prefixes (which arguably is a pain), pyVO quite clearly expects them;
hence, statically map the vr, tr, and vs (on the tables endpoint)
prefixes to the namespace URIs and you should be good.  Regardless of
whether or not pyVO gets fixed, it's a reasonably simple measure on
all XML writers I've looked at in the past ten years (it's been a
pain before that).


However, in the spirit of the golden rule of interoperability ("be
strict in what you produce and lenient in what you accept"), pyVO
probably ought to namespace-normalize xsi:type attributes (which, off
the top of my head, are the only instances of namespaced attribute
values in VOResource).  This would mean doing something like

```
  prefix, tag_name = element.attrs["{...xsi...}type"].split(":")
  element.attrs["{...xsi...}type"] = = f'{namespace_map[prefix]}{tag_name}'
```

(with some robustness additions) in the right place.  I've not
checked how hard it is to get to the parser's namespace map in the
various places this code could sit in.

Once that's in place, all the register_xsi_type decorators would have
to be changed to, say,

```
{http://www.ivoa.net/xml/TAPRegExt/v1.0}TableAccess
```

In my continuing quest to rein in the disasters following the fateful
misdesign of QNames in attribute values (outside of XSLT), I might be
swayed to prepare a PR for that if someone else promises to work out
the github bureaucracy.

**Comment by theresadower** [comment]
At MAST, we are also seeing describe() failing, and I believe it maps to VOSI namespace usage that is difficult to change in the current C# platform running our VOSI endpoints. I need to do a little more digging to prove it's exactly the same, but it is at least related. I don't mind handling PRs and such especially if it would fix our own issues as well.

**Comment by vforchi** [comment]
I wrote the code to generate that XML, and I am using JAXB: I tried to change the namespaces to follow the recommended names, but I had problems with namespaces showing in places where they were not supposed to.
Is the problem coming **only** from the vosi namespace? If so, I could try to fix at least that one.

**Comment by msdemlei** [comment]
On Tue, Apr 06, 2021 at 08:55:35AM -0700, Vincenzo Forchì wrote:
> I wrote the code to generate that XML, and I am using JAXB: I tried
> to change the namespaces to follow the recommended names, but I had
> problems with namespaces showing in places where they were not
> supposed to.

Hm -- that should be orthogonal.  The trouble here is the namespace
*mapping*, i.e., the relationship between the prefix and the URI.

> Is the problem coming **only** from the vosi namespace? If so, I
> could try to fix at least that one.

I'd expect for basic functionality, just getting
http://www.ivoa.net/xml/TAPRegExt/v1.0 mapped to tr would probably
about do it.  For the interfaces, try to get
http://www.ivoa.net/xml/VODataService/v1.1 mapped to vs, too.

**Comment by msdemlei** [comment]
On Thu, Apr 28, 2022 at 09:03:59AM -0700, almicol wrote:
> Back to this old ticket... We deployed our service last year, so now tests can be conducted live:
> 
> import pyvo as vo
> tap = vo.dal.TAPService("http://archive.eso.org/tap_obs")
> tap.describe()
> 
> to get many warnings, and especially a very much truncated list of capabilities:
> 
> `WARNING: UnknownElementWarning: None:1:577: UnknownElementWarning: Unknown element dataModel [pyvo.utils.xml.elements]

Ah.  That looks like a pyvo problem, indeed.  Unless someone beats me
to it, I'll have a look ~ next week.

**Comment by almicol** [comment]
Thanks Markus. If astropy.utils.xml.iterparser is not easily fixable (that would be best), your solution seems a not-offending one, so I would agree with it.

**Comment by msdemlei** [comment]
On Wed, May 04, 2022 at 12:34:32AM -0700, almicol wrote:
> Thanks Markus. If astropy.utils.xml.iterparser is not easily
> fixable (that would be best), your solution seems a not-offending
> one, so I would agree with it. 

There's now PR #323 that ought to fix things for you (and I'd guess
for MAST, too).

**Comment by bsipocz** [comment]
The warnings are now gone for this example.
