### ISSUE TITLE
pyvo installs mimeparse 0.1.3 although python-mimeparse 1.6.0 is already installed

### ISSUE THREAD

**Issue by gcomes** [astropy/pyvo#267]
When I install pyvo with pip, it downloads mimeparse 0.1.3, but on my machine I already have python-mimeparse 1.6.0.
Unless there is a requirement to use such ancient version of mimeparse I think the problem is due to the fact that in the file setup.cfg the line:

 install_requires = astropy requests mimeparse

should be changed to:

 install_requires = astropy requests python-mimeparse

**Comment by pllim** [comment]
I think this was fixed in #276 .
