### ISSUE TITLE
UWS parser doesn't know errorSummary?

### ISSUE THREAD

**Issue by msdemlei** [astropy/pyvo#272]
The following programme:

```
from pyvo.dal import tap

svc = tap.TAPService("http://dc.g-vo.org/tap")
with svc.submit_job("Doofus") as job:
9job.run()
9job.wait()
```

yields:

```
WARNING: UnknownElementWarning: None:1:995: UnknownElementWarning: Unknown element errorSummary [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:1:1044: UnknownElementWarning: Unknown element message [pyvo.utils.xml.elements]
```

although the document returned is UWS- and XSD-valid.  Does anyone
remember why that is so?

If someone is currently working with the code: would you add support for
errorSummary?  Otherwise, please poke me and I'll fix it.

**Comment by pllim** [comment]
I think this was fixed in #276.
