### ISSUE TITLE
Compatibility with python 3.10

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#277]
While I'm trying to add python 3.10 testing to astroquery I run into some compatibility issues for pyvo. Would be nice to fix any possible incompabilities and add 3.10 to the CI matrix, here, too.

 Here is an example run: https://github.com/astropy/astroquery/runs/4077155703

**Comment by andamian** [comment]
@bsipocz - how urgent is this? Only `3.10-dev` is available in `pyenv`. Could this be bundled with `astropy 5.0` dependency or the two have different timelines in `astroquery`?

**Comment by bsipocz** [comment]
If you `brew upgrade pyenv` then 3.10.0 comes up, too 😉  (but also messes up your python, at least I'm now in some trouble with it and am not really able to conveniently switch between versions without using the full paths).

It's not super urgent. Astropy 5.0 should support 3.10, but we're independent of it. For astroquery we also run into python 3.10 incompatibility with mocpy, so I'll push out the next release without the 3.10 support.

**Comment by andamian** [comment]
I'm going to give it a try locally with 3.10-dev - maybe I can fix the code with that.

**Comment by rra** [comment]
https://github.com/astropy/pyvo/pull/262 fixes at least some of the issues seen in the GitHub Actions run above. That's already been merged but there hasn't been a subsequent release, so pyvo from PyPI doesn't work (yet).

**Comment by bsipocz** [comment]
@rra - good point, I'll check this dev version with astroquery later this evening, maybe everything is in place already for a quick release.

**Comment by bsipocz** [comment]
I'm happy to report that the astroquery tests seem to be happy with the current dev version of pyvo.
