### ISSUE TITLE
simple_service_discovery.ipynb notebook gives warnings in cell#2, 6, 7,  8, 9, 10 for simple calls to pyvo.regsearch()

### ISSUE THREAD

**Issue by KenMighell** [astropy/pyvo#286]
`pyvo.__version__='1.2'`

The Jupyter notebook  
`pyvo/examples/notebooks/simple_service_discovery.ipynb`  
issues warnings in cell numbers 2, 6, 7,  8, 9, and 10 for simple calls to pyvo.regsearch().

This script

```
#!/usr/bin/env python3
import pyvo
import warnings

show_warnings = True
if not show_warnings:
    warnings.filterwarnings("ignore", module="pyvo.utils.xml.*")
    print("*** pyvo.utils.xml warnings suppressed ***")

print(pyvo.__version__, "=pyvo.__version__")

services = pyvo.regsearch(servicetype="sia", waveband="x-ray")
# EOF
```

produces these 9 warnings:

```
WARNING: UnknownElementWarning: None:3:1502: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1512: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1540: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1550: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1568: UnknownElementWarning: Unknown element meta [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1643: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1653: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1683: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:3:1693: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
```

Notebook cell numbers 2, 6, 7,  8, 9, and 10 produce the same above errors.
 
Changing the value of the script variable show_warnings to False stops the warnings from being displayed -- at the cost of losing all XML parsing diagnostics.

**Comment by msdemlei** [comment]
On Tue, Jan 11, 2022 at 09:43:40AM -0800, KenMighell wrote:
> WARNING: UnknownElementWarning: None:3:1502: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]
> WARNING: UnknownElementWarning: None:3:1512: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
> WARNING: UnknownElementWarning: None:3:1540: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]

Well, that's because I [the operator of reg.g-vo.org] have been
pushing out an experimental capability (Background:
https://github.com/ivoa-std/TAPRegExt/pull/5).  Since activity on
this is a bit low at the moment, I've switched off the generation of
this capability for now, so the warnings should be gone.

Meanwhile, I'd say that pyVO should re-consider warning against
unknown elements by default.  By IVOA versioning policies,
<https://ivoa.net/documents/Notes/XMLVers>

  It is for this reason that the client side of an IVOA service
  should be forgiving in ignoring elements that it is not expecting.

This doesn't mean we can't warn, but we should have a clear idea why
we do this.

And *if* we do the warning, we should at least not do it for
xsi:type-s we don't know (as in this case).

If we can agree on a certain policy (don't worry about unknown
elements at all/only for known types), I can probably write a PR to
implement it.

**Comment by KenMighell** [comment]
Thanks for the detailed update.

I agree that pyro should reconsider warning about unknown elements by default.

On Jan 12, 2022, at 3:31 AM, msdemlei ***@***.******@***.***>> wrote:


On Tue, Jan 11, 2022 at 09:43:40AM -0800, KenMighell wrote:
> WARNING: UnknownElementWarning: None:3:1502: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]
> WARNING: UnknownElementWarning: None:3:1512: UnknownElementWarning: Unknown element name [pyvo.utils.xml.elements]
> WARNING: UnknownElementWarning: None:3:1540: UnknownElementWarning: Unknown element endpoint [pyvo.utils.xml.elements]

Well, that's because I [the operator of reg.g-vo.org<http://reg.g-vo.org>] have been
pushing out an experimental capability (Background:
https://github.com/ivoa-std/TAPRegExt/pull/5). Since activity on
this is a bit low at the moment, I've switched off the generation of
this capability for now, so the warnings should be gone.

Meanwhile, I'd say that pyVO should re-consider warning against
unknown elements by default. By IVOA versioning policies,
<https://ivoa.net/documents/Notes/XMLVers>

It is for this reason that the client side of an IVOA service
should be forgiving in ignoring elements that it is not expecting.

This doesn't mean we can't warn, but we should have a clear idea why
we do this.

And *if* we do the warning, we should at least not do it for
xsi:type-s we don't know (as in this case).

If we can agree on a certain policy (don't worry about unknown
elements at all/only for known types), I can probably write a PR to
implement it.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fastropy%2Fpyvo%2Fissues%2F286%23issuecomment-1010894393&data=04%7C01%7Ckmighell%40seti.org%7C6a6d940b2a1b43108bd108d9d5b6c089%7Cdeac5258294749c2a474e8ab151104fb%7C0%7C0%7C637775803180516071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SOTBgfvv3a92yCsaDtz1qgkdhT7FBdQgilXliqNPw18%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEGDRSO6E5YQUCHGJQO3TLTUVVKBTANCNFSM5LW5NUBQ&data=04%7C01%7Ckmighell%40seti.org%7C6a6d940b2a1b43108bd108d9d5b6c089%7Cdeac5258294749c2a474e8ab151104fb%7C0%7C0%7C637775803180516071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1m20oFEbRWcYDMdfz3lQay%2BaYGc%2BeY9C0yLlgGXEnUE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckmighell%40seti.org%7C6a6d940b2a1b43108bd108d9d5b6c089%7Cdeac5258294749c2a474e8ab151104fb%7C0%7C0%7C637775803180516071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VPYjxy40pIEXHruF4Gj20mmIVVHiogv%2F%2F%2F92wfRyZrQ%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckmighell%40seti.org%7C6a6d940b2a1b43108bd108d9d5b6c089%7Cdeac5258294749c2a474e8ab151104fb%7C0%7C0%7C637775803180516071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7aqbhVyllJ7%2FRE7Z2U7cbukvpBm7DMrWyyRw6nd9diY%3D&reserved=0>.

**Comment by bsipocz** [comment]
We have removed the examples directory of scripts and notebooks in favour of including and testing them as part of the narrative docs. Therefore I'm closing this issue as not applicable any more.
