### ISSUE TITLE
Fix Zenodo webhook

### ISSUE THREAD

**Issue by pllim** [astropy/pyvo#287]
Currently, even though there is an assigned DOI and an active webhook, GitHub Release is unable to publish successfully to Zenodo. Repo admin needs to contact Zenodo to sort this out. Here is the error message:

*The GitHub OAuth token we have for your account is invalid or expired. Please renew your token by disconnecting and connecting your GitHub account at our \"Linked accounts\" settings page. You can then contact us via our support form to have this release published.*

To see the full payload, repo admin can do the following:

1. Log into zenodo.org website.
2. Click the small arrow next to your username on top right.
3. Click GitHub.
4. Find "pyvo" in the list and click on it.
5. Click on `v1.1 astropy/pyvo: pyvo v1.1` to expand the content.
6. Click on Payload tab.

**Comment by tomdonaldson** [comment]
The issue had to do with the transfer of pyvo to the astropy organization.  Zenodo support was very helpful and was able to straighten that out and trigger previous builds (v0.9.3, v1.0, v1.1, v1.2).

After creating the `v1.2.1` release, I confirmed that it automatically appeared in Zeondo.
