### ISSUE TITLE
adhoc services not working in SCSResults

### ISSUE THREAD

**Issue by trjaffe** [astropy/pyvo#292]
Datalinks aren't working from cone services.  E.g.,
```
import pyvo as vo
taptest=vo.regsearch(keywords=['heasarc'],servicetype='tap')[0]
results=taptest.search(query="select top 10 * from swiftmastr")
results[0].getdatalink()
```
will work fine.  The corresponding cone service (not yet deployed publicly, contact me for a test URL) results in an error
```
results=scstest.search(...)
results[0].getdatalink()
...
AttributeError: 'SCSResults' object has no attribute '_adhocservices'
```

I believe this is due to the fact that the TAPResults is initialized with
`class TAPResults(DatalinkResultsMixin, DALResults):`
while the SCSResults is initialized with
`class SCSResults(DALResults, DatalinkResultsMixin):`
The latter is the wrong order, and the __init__() in the Mixin is never called, and that's where the _adhocservices are collected.  Simply swap the order and it works.  Ours is probably the only service trying to do this.

**Comment by msdemlei** [comment]
On Mon, Jan 24, 2022 at 10:35:28AM -0800, trjaffe wrote:
> I believe this is due to the fact that the TAPResults is initialized with
> `class TAPResults(DatalinkResultsMixin, DALResults):`
> while the SCSResults is initialized with
> `class SCSResults(DALResults, DatalinkResultsMixin):`
> The latter is the wrong order, and the __init__() in the Mixin is
> never called, and that's where the _adhocservices are collected.
> Simply swap the order and it works.  Ours is probably the only
> service trying to do this.

I agree datalink on cone search should work; I've not investigated
why the MRO would influence this behaviour, but it's not implausible.
So: Would you prepare a PR?

**Comment by zoghbi-a** [comment]
_Originally posted by @andamian in https://github.com/astropy/pyvo/issues/320#issuecomment-1119114392_

> I'm seeing this potential problem (base class in the wrong spot) in other classes: `SIAService`, `SIAQuery` etc. Shouldn't those be fixed as well or it's considered too risky for the potential benefit?

I am not sure if these should be handled here, or separately.

**Comment by bsipocz** [comment]
I suppose this has been resolved, please reopen if that is not the case.
