### ISSUE TITLE
Current PyVO release incompatible with latest astropy

### ISSUE THREAD

**Issue by stefanv** [astropy/pyvo#294]
PyVO current release depends on `wraps` which is no longer exposed in `astropy.utils`.  This is fixed on the main branch, but has not been released.  Please mint a release so that latest PyVO and astropy can work together.

**Comment by andamian** [comment]
@stefanv what version are you running? 1.2 released a couple of weeks ago should contain the fix.

**Comment by stefanv** [comment]
Thanks for your response @andamian. Looks like the fix is in 1.2.1 (we were pinned to 1.2), so I will switch to that instead.

Sorry for the noise.
