### ISSUE TITLE
Rework tox to rely on `setup.cfg` to install dependencies

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#310]
#308 highlights that some of the dependencies are not declared properly, yet it wasn't causing any issues in CI as those packages are hard-wired in the tox config. Ideally they should be handled via the `extras` sections in `tox.ini` that would indicate which `extras_require` from `setup.cfg` has to be installed.

**Comment by olaurino** [comment]
Would you like me to add that to #308?

**Comment by bsipocz** [comment]
If you would like, please do by all means. For examples, the tox and setup configs of astropy core, photutils, and astroquery are all OK to be consulted.

**Comment by olaurino** [comment]
ok. I'll rework #308 to make it fail without the proper `setup.cfg` additions. Then I'll add the dependencies back to make CI work.
