### ISSUE TITLE
CI should not run on forks

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#318]
I keep getting emails that tests are run on my fork for the branch I opened my latest PR from. CI should be disabled for forks.

example subject line: `[bsipocz/pyvo] Run failed: CI - tests_raise_warnings (196d402)`

**Comment by msdemlei** [comment]
On Thu, Apr 28, 2022 at 09:59:59AM -0700, Brigitta Sipőcz wrote:
> I keep getting emails that tests are run on my fork for the branch
> I opened my latest PR from. CI should be disabled for forks.

+1 (not to mention power savings)
