### ISSUE TITLE
Fix mocking datalink tests

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#325]
The several tests in [pyvo/dal/tests/test_datalink.py](https://github.com/astropy/pyvo/pull/317/files#diff-9eaedd7641591eba7e233c3a17b1a3a45db788ca92dd5d1429e4065f4b0d4025) are using mock fixtures, yet the are failing with remote-data access as they do a `utils.vocabularies.get_vocabularity() call`.

It didn't cause a problem until now as the test configs weren't in fact picked up properly.  

I've temporarily added the `remote-data` decorator to these tests in #317, they should be removed once the mocking is fixed.
Some basic summary of my findings are in the thread in that PR: https://github.com/astropy/pyvo/pull/317/files#r867273353

**Comment by msdemlei** [comment]
PR #326 ought to fix this -- could you have a look?
