### ISSUE TITLE
Registry doc cleanup

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/pyvo#337]
A couple items to clean up in the registry rst doc as follow up to #289:

1.   `tables = resources[4].get_tables()` should get a `# doctest: +IGNORE_WARNINGS` to ignore unrelated warnings during doctests.
2.   There are 2 "all-VO" queries that appropriately have `.. doctest-skip::` since they would take a long time and frequently fail.  Since that code is for illustration purposes only, consider:
      - clarifying those limitations with a comment
      - don't skip the example, but modify it to limit its run time and frailty (e.g., limit it to a couple iterations only with a suitable comment on how it would look for all-VO)

**Comment by bsipocz** [comment]
The first point has been addressed in #358, and a separate issue #359 has been opened for it (sorry, I didn't see this one in time).

**Comment by msdemlei** [comment]
Since there's #359, closing this.
