### ISSUE TITLE
DOC BUG: access_url vs get_service

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#339]
I'm nitpicking the `main` branch before it lands in the release while running the tests of the navo notebooks:

I suppose the notebooks is not exactly backward compatible as these changes are supposed to be fixing a bug/inconsistency. Yet, it's a failure that may use some document patching of pyvo. Full log is e.g. here, but I also include the traceback below in the details as the log is only available for 90 days: https://github.com/NASA-NAVO/navo-workshop/runs/6802210768?check_suite_focus=true

With pyvo<1.4 one would get a string from the `access_url` method. Now, after the refactoring, it's an error message to suggest using `get_service`, but that returns a service instance rather than a string, so ideally the error message needs an update.

Also,  extending the docstring of `get_service` would be nice to say what it returns, so one doesn't have to consult the code itself.

<details>

UseCase_II.ipynb ......F.............                                    [ 86%]
UseCase_III.ipynb ...........FF..............                            [100%]
=================================== FAILURES ===================================
___________________________ UseCase_II.ipynb::Cell 6 ___________________________
Notebook cell execution failed
Cell 6: Cell execution caused an exception
Input:
uv_services.to_table()[
    np.array(['GALEX' in u.short_name for u in uv_services])
    ]['ivoid', 'short_name', 'access_url']
Traceback:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [7], in <cell line: 1>()
   (...)
    243  tc[1:3] # <TableColumns names=('b', 'c')>
    244"""
    245ifisinstance(item, str):
--> 246returnOrderedDict.__getitem__(self,item)
    247elifisinstance(item, (int, np.integer)):
    248returnlist(self.values())[item]
KeyError: 'access_url'
__________________________ UseCase_III.ipynb::Cell 12 __________________________
Notebook cell execution failed
Cell 12: Cell execution caused an exception
Input:
author = 'Eichhorn'
for record in resources: 
    names=record.creators
    if 'Eichhorn' in names[0]: 
        print("For %s: " %record.short_name)
        print("     Reference URL: %s" %record.reference_url)
        print("     Access URL: %s" %record.access_url)
Traceback:
---------------------------------------------------------------------------
DALQueryError                             Traceback (most recent call last)
Input In [13], in <cell line: 3>()
      6print("For %s: "%record.short_name)
      7print("     Reference URL: %s"%record.reference_url)
----> 8print("     Access URL: %s"%record.access_url)
File ~/work/navo-workshop/navo-workshop/.tox/py310-test-devdeps/lib/python3.10/site-packages/pyvo/registry/regtap.py:504, in RegistryResource.access_url(self)
    502return access_urls[0]
    503else:
--> 504raise dalq.DALQueryError(
    505"No unique access URL.  Use get_service.")
DALQueryError: No unique access URL.  Use get_service.
=============================== warnings summary ===============================
.tox/py310-test-devdeps/lib/python3.10/site-packages/_pytest/nodes.py:633: 12 warnings
  /home/runner/work/navo-workshop/navo-workshop/.tox/py310-test-devdeps/lib/python3.10/site-packages/_pytest/nodes.py:633: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to IPyNbFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)
CS_Catalog_Queries.ipynb: 20 warnings
CS_Image_Access.ipynb: 14 warnings
CS_Spectral_Access.ipynb: 9 warnings
CS_UCDs.ipynb: 11 warnings
CS_VO_Tables.ipynb: 5 warnings
Exercise_I.ipynb: 17 warnings
Exercise_II.ipynb: 16 warnings
Exercise_III.ipynb: 21 warnings
QuickReference.ipynb: 15 warnings
UseCase_I.ipynb: 34 warnings
UseCase_II.ipynb: 21 warnings
UseCase_III.ipynb: 28 warnings
  /home/runner/work/navo-workshop/navo-workshop/.tox/py310-test-devdeps/lib/python3.10/site-packages/zmq/_future.py:498: DeprecationWarning: There is no current event loop
    f = future or self._Future()
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED UseCase_II.ipynb::Cell 6
FAILED UseCase_III.ipynb::Cell 11
FAILED UseCase_III.ipynb::Cell 12
=========== 3 failed, 196 passed, 223 warnings in 282.28s (0:04:42) ============
ERROR: InvocationError for command /home/runner/work/navo-workshop/navo-workshop/.tox/py310-test-devdeps/bin/pytest --nbval (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py310-test-devdeps: commands failed
Error: Process completed with exit code 1.

<\details>

**Comment by tomdonaldson** [comment]
This was mostly addressed by #341 which enabled the `access_url` accessor and improved documentation for `RegistryResource`.  We've decided to live without the `access_url` column in the `to_table()` output of `RegistryResults`.

**Comment by msdemlei** [comment]
On Wed, Jun 08, 2022 at 02:53:57PM -0700, Brigitta Sipőcz wrote:
> With pyvo<1.4 one would get a string from the `access_url` method.
> Now, after the refactoring, it's an error message to suggest using
> `get_service`, but that returns a service instance rather than a
> string, so ideally the error message needs an update.

This is fixed in PR #341.

> Also,  extending the docstring of `get_service` would be nice to
> say what it returns, so one doesn't have to consult the code
> itself.

I've tried to do a better job explaining what's coming back also in
PR #341.
