### ISSUE TITLE
UnitsWarnings on query

### ISSUE THREAD

**Issue by EfremBraun** [astropy/pyvo#347]
When I run the following (taken from https://pyvo.readthedocs.io/en/latest/dal/index.html, just changing which SSAService I'm using):
```
import pyvo as vo
from astropy.coordinates import SkyCoord
from astropy.units import Quantity

pos = SkyCoord.from_name('NGC 4993')
size = Quantity(0.5, unit="deg")

ssa_service = vo.dal.SSAService("https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&products=hitomi.obs.sxs.prod.spi")
ssa_results = ssa_service.search(pos=pos, diameter=size)
```
the result is correct, but it also prints:
```
WARNING: UnitsWarning: Unit 'degree' not supported by the VOUnit standard.  [astropy.units.format.vounit]
WARNING: UnitsWarning: Unit 'mjd' not supported by the VOUnit standard. Did you mean MD, MJ, Md, mD, mJ or md? [astropy.units.format.vounit]
WARNING: UnitsWarning: Unit 'meter' not supported by the VOUnit standard.  [astropy.units.format.vounit]
```

I see "degree", "mjd", and "meter" in the URL of https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&products=hitomi.obs.sxs.prod.spi, but I would think that performing a query on the service shouldn't result in warnings. Not sure if this is a bug in the SSA service or in PyVO...

**Comment by msdemlei** [comment]
On Mon, Aug 08, 2022 at 03:11:01PM -0700, Efrem Braun wrote:
> ssa_service = vo.dal.SSAService("https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&products=hitomi.obs.sxs.prod.spi")
>
> WARNING: UnitsWarning: Unit 'degree' not supported by the VOUnit standard.  [astropy.units.format.vounit]
> WARNING: UnitsWarning: Unit 'mjd' not supported by the VOUnit standard. Did you mean MD, MJ, Md, mD, mJ or md? [astropy.units.format.vounit]
> WARNING: UnitsWarning: Unit 'meter' not supported by the VOUnit standard.  [astropy.units.format.vounit]

These are (minor) bugs in the service and should be reported to the
service operators.  Which brings me to the question: Where does the
access URL come from?  You see, I can't find it in the Registry.

For registered services, you can paste the access URL into the form
at

http://dc.zah.uni-heidelberg.de/wirr/q/ui/fixed?field0=accurl&operator0=%3D&operand0=

to find out who to contact (or use RegTAP, or use the get_contact()
method on a result you get back from pyvo's registry.search in pyVO's
next release).  In this particular case, you probably want to contact
***@***.***

I won't close the bug in case I misunderstood you -- but if this
addresses your concern, would you close this bug yourself?

**Comment by EfremBraun** [comment]
The registered URL is "https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&". I just added "products=hitomi.obs.sxs.prod.spi" to the end. But the same error appears with the registered URL.

It looks like the contact person is request@athena.gsfc.nasa.gov. I'll send them an email with the issue.

And yes, if this issue belongs to them and not to pyVO, I'll of course close the issue.
