### ISSUE TITLE
"date" parameter does not work with SSA search for certain services

### ISSUE THREAD

**Issue by EfremBraun** [astropy/pyvo#350]
I've found another error relating in pyVO which only appears with the https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&" service. Based on https://github.com/astropy/pyvo/issues/347, I suspect this is an issue with the service rather than with pyVO, but I wanted to check.

```
import pyvo as vo
from astropy.coordinates import SkyCoord
from astropy.time import Time
import astropy.units as u
 
size = u.Quantity(0.5, unit="deg")
time = Time(('2015-01-01T00:00:00', '2018-01-01T00:00:00'), format='isot', scale='utc')
 
# Example from https://pyvo.readthedocs.io/en/latest/dal/index.html#simple-spectrum-access
pos = SkyCoord.from_name('Eta Carina')
ssa_service = vo.dal.SSAService("http://www.isdc.unige.ch/vo-services/lc")
ssa_results = ssa_service.search(pos=pos, diameter=size, time=time)
table = ssa_results.to_table()
print(table)
 
# Example using HEASARC's Hitomi search
pos = SkyCoord.from_name('perseus cluster')
ssa_service = vo.dal.SSAService('https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&')
ssa_results = ssa_service.search(pos=pos, diameter=size, time=time)
table = ssa_results.to_table()
print(table)
```

The two searches are identical except for the choice of SSA service. The former works, but the latter fails with the following error:
```
Traceback (most recent call last):
  File "/Users/edbraun/Documents/xslide-git-repos/xslidepy/xslidepy/test.py", line 17, in <module>
    ssa_results = ssa_service.search(pos=pos, diameter=size, time=time)
  File "/Users/edbraun/opt/anaconda3/envs/xslide/lib/python3.9/site-packages/pyvo/dal/ssa.py", line 213, in search
    return self.create_query(
  File "/Users/edbraun/opt/anaconda3/envs/xslide/lib/python3.9/site-packages/pyvo/dal/ssa.py", line 570, in execute
    return SSAResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/Users/edbraun/opt/anaconda3/envs/xslide/lib/python3.9/site-packages/pyvo/dal/adhoc.py", line 111, in __init__
    super().__init__(votable, url=url, session=session)
  File "/Users/edbraun/opt/anaconda3/envs/xslide/lib/python3.9/site-packages/pyvo/dal/query.py", line 320, in __init__
    raise DALQueryError(self._status[1], self._status[0], url)
pyvo.dal.exceptions.DALQueryError: Unsupported time requested.
```

Removing the "time" parameter from the Hitomi search gets the search to work.

**Comment by msdemlei** [comment]
I've replied via mail, but that mail is still hanging somewhere.  In that mail, I had said the service *may* be all right by SSAP after all.  Turns out it is not, even ISO literals without microseconds cause the thing to fail.  So – it is a service bug indeed (temporal constraints to SSAP are uncommon so far, so it's particularly meritorious to get them to work reliably before many people will hit such bugs).

**Comment by EfremBraun** [comment]
Okay. I just sent another email to request@athena.gsfc.nasa.gov to report the issue with the service.

**Comment by msdemlei** [comment]
On Mon, Aug 15, 2022 at 01:24:35PM -0700, Efrem Braun wrote:
> time = Time(('2015-01-01T00:00:00', '2018-01-01T00:00:00'), format='isot', scale='utc')
> # Example using HEASARC's Hitomi search
> pos = SkyCoord.from_name('perseus cluster')
> ssa_service = vo.dal.SSAService('https://heasarc.gsfc.nasa.gov/xamin/vo/ssa?table=hitomaster&')
> ssa_results = ssa_service.search(pos=pos, diameter=size, time=time)
> ...
>     raise DALQueryError(self._status[1], self._status[0], url)
> pyvo.dal.exceptions.DALQueryError: Unsupported time requested.

That's not *clearly* heasarc's fault.  But not exactly pyvo's either.
It's an example of why I'm always pushing for minimal standards
(which ISO 8601 certainly is not).

You see, pyVO formats your time constraint to

  2015-01-01T00:00:00.000/2018-01-01T00:00:00.000

SSA says that the TIME parameter supports "a restricted subset of ISO
8601 format" but fails to conclusively define these restrictions.  It
says:

  Allowable ISO8601 formats include the date (e.g., yyyy-mm-dd with
  the month and day fields being optional, the minimum being yyyy),
  or the date-time (e.g., yyyy-mm- ddThh:mm:ss).

(and something on time zones that I'm sure no service on this planet
actually implements correctly).  So, the milliseconds pyVO includes
are not explicitly covered -- but not explicitly excluded either.

In the spirit of "be strict in what you produce but lenient in what
you accept", I'll prepare a PR that will nuke the milliseconds (I
cannot imagine a use case where these would be relevant for the
remaining lifetime of SSAP), but I'd say it would be good to ask
heasarc to not fail when microseconds are present.
