### ISSUE TITLE
AsyncTAPJob's "query" attribute is not robust to case variation among community TAP servers

### ISSUE THREAD

**Issue by gpdf** [astropy/pyvo#356]
We have recently noticed that the "query" attribute of AsyncTAPJob (https://pyvo.readthedocs.io/en/latest/api/pyvo.dal.AsyncTAPJob.html#pyvo.dal.AsyncTAPJob.query) does not work with either the Rubin Observatory TAP service or the CADC TAP service under some conditions.

"query" works by interrogating the `<uws:parameters>` element of the UWS job's XML for a `<uws:parameter>` whose "id" attribute is "query" - that is, it's trying to find the value of the URL parameter "QUERY" from the original TAP invocation, which UWS says should be reflected back in this XML.

The problem here stems from the fact that, while the IVOA standards, including TAP, generally explicitly document the names of the services' URL query parameters in UPPERCASE, the DALI standard makes clear that _in the URL interface, a conformant service must accept any case rendering of the parameter name_.  So "query", "QUERY", and "Query", for instance, are equally valid.

The UWS standard does not appear to say anything about how query parameters should be reflected back - in their original case, or in a standardized case.  It appears that some of the well-known community TAP services return them in their original case, while others force them to lowercase.

Notably, the OpenCADC TAP service seems to return parameters in their original case, which seems like a reasonable thing to do in the absence of words to the contrary in UWS.  The Rubin Observatory also uses this code base, so our TAP service is affected by the same issue.

There is existing community code that generates queries with the parameter names in uppercase, following the style of all the IVOA documentation (though, of course, this is not required) and we are currently unable to work successfully with the resulting UWS jobs.

It seems as if PyVO should apply the same case-blindness here that DALI requires to be used on input, and recognize any case form of "QUERY" in its implementation.

The Rubin team is willing to make this change but wanted to trigger a discussion first to see if there will be resistance to this.

Potentially interested parties: @rra @athornton @pdowler @cbanek

**Comment by msdemlei** [comment]
On Thu, Sep 15, 2022 at 04:56:12PM -0700, gpdf wrote:
> It seems as if PyVO should apply the same case-blindness here that
> DALI requires to be used on input, and recognize any case form of
> "QUERY" in its implementation.

I agree that UWS parameters need to be interpreted case-insensitively
in a DALI context.  I sure don't like it, and I've fought
case-insenstivity whenever I could, but anything else is insane here.
We should note this in DALI-next.  Pat?

> The Rubin team is willing to make this change but wanted to trigger
> a discussion first to see if there will be resistance to this.

That'd be great - thanks!
