### ISSUE TITLE
Allow registry.vao module to access multiple mirrors of the registry

### ISSUE THREAD

**Issue by RayPlante** [astropy/pyvo#36]
A mirror of the VAO registry is expected to be deployed at CFA.  `registry.vao` should be updated to enable access to multiple mirrors.

**Comment by funbaker** [comment]
``registry.vao`` was replaced by ``registry.regtap``

**Comment by RayPlante** [comment]
Does the VAO api service still exist?  As you might have guessed, the registry package was meant to support multiple interfaces via multiple modules.  If the service is no longer available, then it makes sense to pull the `vao` module.

**Comment by funbaker** [comment]
I assumed that the VAO Registry was some kind of proprietary interface. Mea culpa.

It can be brought back via git, but wouldn't it make sense to use the more flexible regtap interface anyway?

**Comment by RayPlante** [comment]
Yes, it would, and it would make sense to make the regtap more prominent in the registry level module.  However, if there are scripts out there already using the vao interface (which I seem to recall at least one tool), then its disappearance would break them.

**Comment by cbanek** [comment]
Issue #158 points out that the vao module was deleted already and it seems quite a while ago.  This seems like a feature request on something that was taken out, as was pointed out in this issue.  If no one has any objections, I'll close this one out in a bit.

**Comment by msdemlei** [comment]
Sure, go ahead.  It was an omission on our side not to have done it
when we dropped registry.vao.
