### ISSUE TITLE
CI: have more strict codestyle check

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#370]
Running flake8 currently gives these errors. I don't really see any good reason not to include many more if these in the check, and would rather suggest to run the CI with an exclude list rather than with a select list.

```
9     E115 expected an indented block (comment)
1     E117 over-indented
1     E122 continuation line missing indentation or outdented
20    E124 closing bracket does not match visual indentation
146   E128 continuation line under-indented for visual indent
1     E129 visually indented line with same indent as next logical line
3     E131 continuation line unaligned for hanging indent
41    E225 missing whitespace around operator
1     E228 missing whitespace around modulo operator
12    E231 missing whitespace after ':'
8     E252 missing whitespace around parameter equals
3     E261 at least two spaces before inline comment
1     E265 block comment should start with '# '
12    E275 missing whitespace after keyword
1     E303 too many blank lines (3)
23    E501 line too long (250 > 110 characters)
1     E712 comparison to False should be 'if cond is False:' or 'if not cond:'
10    F401 'PIL.Image' imported but unused
1     F821 undefined name 'base'
5     F841 local variable 'cons' is assigned to but never used
38    W505 doc line too long (83 > 79 characters)
```

**Comment by andamian** [comment]
Agree. I've noticed it tended to be too lenient but never got to investigate the cause. Without the select list there are 380 errors - a bit time consuming to fix. We could dedicate one or more PRs just to this or do it gradually with other PRs. I prefer the first approach.

**Comment by bsipocz** [comment]
👍 for doing it separately. If you want to, I can shuffle a few into https://github.com/astropy/pyvo/pull/371, or indeed open a totally separate for it. 
With autopep8, and the changes in doc line length from #371, the total changes to ~40 errors, so I think it would be reasonably manageable.

**Comment by andamian** [comment]
Oh. If you can do that, then #371 is a good place to shuffle at least the easy ones and keep the others for later. Thanks for doing this.

**Comment by bsipocz** [comment]
@andamian - This is now added to #371 which is now good to go.
