### ISSUE TITLE
`to_qtable` method in `TAPResults` to generate a table of quantities

### ISSUE THREAD

**Issue by andamian** [astropy/pyvo#381]
Posting this on behalf of a user.

Assuming `results` is a `TAPResults` object, this works:
```
from astropy.table import QTable
qt = QTable(results.to_table())
```

but this requires users to be familiar with `QTable`

Can a `TAPResults.to_qtable` (or `to_quantity_table()`) method be added to make this useful feature more obvious?

Note: this will probably go in `DALResults` class

**Comment by msdemlei** [comment]
On Wed, Oct 26, 2022 at 04:14:54PM -0700, Adrian wrote:
> Posting this on behalf of a user.
> 
> Assuming `results` is a `TAPResults` object, this works:
> ```
> from astropy.table import QTable
> qt = QTable(results.to_table())
> ```
> 
> but this requires users to be familiar with `QTable`
> 
> Can a `TAPResults.to_qtable` (or `to_quantity_table()`) method be added to make this useful feature more obvious?
> 
> Note: this will probably go in `DALResults` class

Sounds like a useful and simple addition to me.  Does anyone see a
downside other than polluting DALResult's namespace a tiny bit?

**Comment by andamian** [comment]
Re namespace pollution, is it preferable to add a flag to `to_table` instead?

**Comment by bsipocz** [comment]
Is there any reason that to_table not to return a QTable instead? It's basically the advanced version of Table, knows everything that a Table does and more and it's basically historical reasons only that it's a separate class.
