### ISSUE TITLE
'cgi' is deprecated by Python 3.11 and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by Cadair** [astropy/pyvo#382]
You (like me) use the `cgi.parse_header` function:

https://github.com/astropy/pyvo/blob/a7f247f6d7c6edcef5b879e5ade54498bee9b86a/pyvo/dal/mimetype.py#L78

This is deprecated in Python 3.11. 

It's pretty easy to just copy the required code out of the standard library though: https://github.com/Cadair/parfive/commit/3da1c9126ada4412fecaeaa4fa2568d1c792d31b#diff-c397da66924109b8a9e29d6851a7707304612d0c2e52c0dcf2f6bdd7b929c453R25-R54

**Comment by andamian** [comment]
Thanks for the heads up. PEP-0594 offers a different option that doesn't require duplicating the deprecated code:

https://peps.python.org/pep-0594/#cgi

**Comment by Cadair** [comment]
Yeah, the return type is slightly different which is annoying enough I was lazy.
