### ISSUE TITLE
ENH: pyvo.io.vosi.parse_capabilities to parse from str

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#388]
Use case:

there is a `Response` instance, and it would be generally useful to be able able to directly parse `response.text` rather than writing it out to an XML file and then parsing it as a file.

**Comment by msdemlei** [comment]
On Sat, Nov 26, 2022 at 06:12:12PM -0800, Brigitta Sipőcz wrote:
> Use case:
> 
> there is a `Response` instance, and it would be generally useful to be able able to directly parse `response.text` rather than writing it out to an XML file and then parsing it as a file.

Absolutely -- before I start writing the code: is this a statement of
intention to add the feature or a request that someone else should
look into it?

**Comment by bsipocz** [comment]
This ultimately was a side track for addressing the problem I hoped to get to the bottom of, but unfortunately this wasn't the only blocker and the downstream code may need a proper refactor even without this enhancement.
Anyway, that's being said, I haven't started working on this, and have no immediate intention (==time) to do it in the near future.

**Comment by jwfraustro** [comment]
This would be handy. I've just recently run into a similar situation and had to side-step it by using:

`parse_tables(io.BytesIO(resp.content))`

Reading it directly from a string would be great.

**Comment by bsipocz** [comment]
Oh, indeed that could work. I was so much fixated on the `response.text` that haven't even through about parsing `response.content` instead. 

Is there any other use cases in mind when the xml would be in a string? I just feel that the requests Response case has just lost its foundation.

**Comment by jwfraustro** [comment]
It's a bit more niche for us but still basically the same thing-- it came up out of a need to validate that our VOSI endpoint responses properly conformed to spec and the `parse_*` functions are very convenient to do that. Our TAP service is being built on FastAPI and uses requests/httpx under the hood during unit tests to test the endpoints, so we ended up back at the similar issue of needing to convert it from a Response to pass it in.

**Comment by msdemlei** [comment]
I've had a look at this, and frankly, I think the BytesIO wrapper is straightforward enough for cases where this kind of thing is necessary (it's not like it's something your average astronomer would have to regularly do).

So... I won't touch anything there and would tend to WONTFIX (well: we could perhaps look whether there's a good place to document the pattern, as it applies to several other such functions, too).

While having a look, I noticed the documentation claims:

```
    Returns
    -------
    votable : `~pyvo.io.vosi.endpoint.CapabilitiesFile` object
```

I don't think that should be called "votable", as it has nothing to do with votables whatsoever.  Similar for the two other VOSI functions.  If someone touches the file, it'd be great if they could just drop the "votable" part.
