### ISSUE TITLE
BUG: hardlimit should not be mandatory

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#389]
I'm trying to use the mast registry, but unfortunately run into this issue of undefined hard limit from the server side. I believe we should be able to handle this case and at worst issue a Warning rather than an exception.

I will likely open other, separate issues regarding the current difficulty of using other registry URLs. 

```
---------------------------------------------------------------------------
DALServiceError                           Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 image_services1 = pyvo.regsearch(servicetype='sia')

File /srv/conda/envs/tractor/lib/python3.10/site-packages/pyvo/registry/regtap.py:158, in search(keywords, servicetype, waveband, datamodel, includeaux)
    148 query = """SELECT DISTINCT rr.interface.*, rr.capability.*, rr.resource.*
    149 FROM rr.capability
    150 NATURAL JOIN rr.interface
   (...)
    154     ("WHERE " if wheres else "") + " AND ".join(wheres)
    155 )
    157 service = tap.TAPService(REGISTRY_BASEURL)
--> 158 query = RegistryQuery(service.baseurl, query, maxrec=service.hardlimit)
    159 return query.execute()

File /srv/conda/envs/tractor/lib/python3.10/site-packages/pyvo/dal/tap.py:205, in TAPService.hardlimit(self)
    203 except AttributeError:
    204     pass
--> 205 raise DALServiceError("Hard limit not exposed by the service")

DALServiceError: Hard limit not exposed by the service
```

**Comment by msdemlei** [comment]
On Wed, Dec 21, 2022 at 04:09:10PM -0800, Brigitta Sipőcz wrote:
> I'm trying to use the mast registry, but unfortunately run into this issue of undefined hard limit from the server side. I believe we should be able to handle this case and at worst issue a Warning rather than an exception.

That's with PR #375 merged?

> I will likely open other, separate issues regarding the current
> difficulty of using other registry URLs. 

Can you hold back on this PR #386 is merged?  @tomdonaldson: Can we
look at unfreezing #386 from your side?

**Comment by bsipocz** [comment]
> That's with PR [#375](https://github.com/astropy/pyvo/pull/375) merged?

you're right, this is resolved on the `main` branch, thanks for pointing out. (the negative side effect of testing things in production, on a remote server, rather than in my usual, nice and cosy dev environments.)

And yes, I've seem [#386](https://github.com/astropy/pyvo/pull/386) after making the comment above, so no need for opening an issue for that either.
