### ISSUE TITLE
MAINT: avoid overwriting variables

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#390]
The current practice of overwriting variables is not exactly debugging friendly and I would suggest to not reuse variable names. E.g. in tap.py:

```
        query = TAPQuery(
            baseurl, query, mode="async", language=language, maxrec=maxrec,
            uploads=uploads, session=session, **keywords)
```

There maybe other examples, too, the one I run into originally has been cleanup already from regtap and an upgrade solved the issue locally.

**Comment by msdemlei** [comment]
On Wed, Dec 21, 2022 at 04:23:14PM -0800, Brigitta Sipőcz wrote:
> The current practice of overwriting variables is not exactly debugging friendly and I would suggest to not reuse variable names. E.g. in tap.py:
> 
> ```
>         query = TAPQuery(
>             baseurl, query, mode="async", language=language, maxrec=maxrec,
>             uploads=uploads, session=session, **keywords)
> ```

Ummm... this looks rather ideomatic to me... Why is this giving you a
headache and what would like to see instead?

**Comment by bsipocz** [comment]
This doesn't give me a headache, but simply makes future debugging more difficult, in case something goes wrong with the next line. 

So, to turn around your question, why is this better and preferably, and offering any extra in any scenarios compared to calling it e.g.` tap_query = TAPQuery(baseurl, query,...)` to leave easy access for both the instance and the input string?

**Comment by msdemlei** [comment]
On Thu, Dec 22, 2022 at 08:55:03AM -0800, Brigitta Sipőcz wrote:
> preferably, and offering any extra in any scenarios compared to
> calling it e.g.` tap_query = TAPQuery(baseurl, query,...)` to leave

Ah, now I got you.  Sorry, I had not understood the "overwriting
variables" and was staring at the constructor call.  That way, I
missed that the name query was used in the function body once for the
query string to be sent to the service and once again for the query
object [that's in case other people also had my problem].

I agree that that is an odious practice, not only with a view to code
clarity but also when we think about JITs and other components that
may want to do type inference one day.

So, I'm in for helping to clean this up.  Do you have a plan?

**Comment by bsipocz** [comment]
No plans, I may get to this as part of a holiday filler, but it's a bit unlikely as I have other side projects already lined up as well.

**Comment by bsipocz** [comment]
I've run into another similar case where astropy.time got overwritten with a local variable, so started to systematically cleanup all `Redefining name 'xyz' from outer scope` pylint issues. 

Most of the cases are banal, but there a few where I'm fully sure what to do:
https://github.com/astropy/pyvo/blob/main/pyvo/utils/xml/elements.py#L265..L266

**Comment by msdemlei** [comment]
On Tue, Jan 31, 2023 at 02:06:28PM -0800, Brigitta Sipőcz wrote:
> Most of the cases are banal, but there a few where I'm fully sure what to do:
> https://github.com/astropy/pyvo/blob/main/pyvo/utils/xml/elements.py#L265..L266

I'll admit that some of the XML parsing magic done in pyvo perhaps is
a bit overly clever.  At least I'd have to think hard if I had to
predict what it actually is that goes in as tag and data in this case
and why the inner function can just discard it.

Anyway, discard is what it does, and so until someone does further
research why the tag and data arguments are irreleveant here, I'd
say just replacing tag and data with tag_ignored and data_ignored in
the formal argument list would be a small gain in comprehensibility,
and it'd fix the warning...

If you don't like this, poke me and I'll figure out why tag and data
really can be discarded.
