### ISSUE TITLE
BUG: `sphinx-build -W` doesn't complain about missing references

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#411]
This is not a pyvo issue, but upstream, however I'm opening the issue here while we try to figure out the scope of the problem and where it belongs (sphinx, or sphinx-automodapi or somewhere else). 
Ideally I want these linking problems to create a sphinx warning and a failing build (after all we use `-W`), but somehow it's not happening, instead these are silently rendered boldface.

There are a couple class references that are not resolved to links here: https://pyvo.readthedocs.io/en/latest/registry/index.html, e.g. `pyvo.registry.RegistryResults` and `pyvo.registry.RegistryResource`.

These classes have their API docs, but at a different namespace, so while we can easily and quickly fix this for pyvo (workaround is to add the correct API location in the docs, but maybe also revisit this in #407 to make sure the narrative and API docs agree and use all examples from the primarily intended namespace).

Pinging @pllim as a heads up, as this problem may exists elsewhere in the astropy world, and also pinging @rossbar who has the best understanding of intersphinx.

**Comment by pllim** [comment]
AFAIK, it only complains if you set nitpicky to True but this repo does not have that set. Please see if https://github.com/astropy/astropy/blob/a0885a98841419c7bf9249fc9f75207b5259a18f/docs/conf.py#L276 helps. 🤞

**Comment by bsipocz** [comment]
Oh, good catch. Yet the build log should have the warnings in there, shouldn't it?

**Comment by bsipocz** [comment]
OK, so with nitpicky, I see 212 warnings. A bit worse situation that I was hoping for 😞

**Comment by pllim** [comment]
> Yet the build log should have the warnings in there, shouldn't it?

That I am not sure. Sphinx has changed a lot over the years. 😬 

But looks like setting nitpicky is doing what you want. Hopefully one fix can address multiple warnings. Good luck. 🤞

**Comment by rossbar** [comment]
Just to add - the situation *might* not be as dire as it initially seems, especially for projects that use the numpydoc format for docstrings. The reason being that the numpydoc standard recommends parameter names be enclosed in single backticks, but this conflicts with the default sphinx role (usually `py:obj`). This means that if you follow numpydoc's formatting rule to the letter, you are likely introducing a bunch of broken links in your docs (as sphinx will try to link all references to the parameters in the docstring).

This is a numpydoc problem, but it definitely makes the nitpicky warning situation far worse.

**Comment by bsipocz** [comment]
Here most of the problems are due to the missing API references, but indeed the situation is not as dire as I first thought and why I dragged both of you into this. Adding a few more API docs would indeed fix the majority of the problems (and anyway, those are valid concerns, if something is referenced in the docs then they should be public API anyway, or removed as a references). 
We also have a few of the single backticked parameters, too, but I'll just double them up for now as our usual workaround of the numpydoc problem.
