### ISSUE TITLE
DOC: all-VO query is non functional

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#412]
While the main purpose of the snippet is demonstration of the looping through all VO resources, the pseudo-code is not functional as is (aka it's not enough to remove the `break`, even though the narrative suggests it). I would suggest to refactor the snippet a bit and add some testing for it, too.

E.g. in the current form e.g. `vstack` is not working, the dtype of the results are either `object` or a string type causing a 
```
astropy.table.np_utils.TableMergeError: The 'dataproduct_type' columns have incompatible types: ['object', 'object', 'object', 'object', 'str512', 'str8160', 'object', 'object', 'str4096', 'object']
```

**Comment by msdemlei** [comment]
On Thu, Jan 26, 2023 at 05:01:05PM -0800, Brigitta Sipőcz wrote:
> E.g. in the current form e.g. `vstack` is not working, the dtype of the results are either `object` or a string type causing a
> ```
> astropy.table.np_utils.TableMergeError: The 'dataproduct_type' columns have incompatible types: ['object', 'object', 'object', 'object', 'str512', 'str8160', 'object', 'object', 'str4096', 'object']

Oh dear.  My spontaneous idea for a minimally stressful query clearly
*and* the vstack trick in one snippet was a bad one.  I frankly had
not considered that strings still are tricky in a VOTable/record
array setting.  The original of this query only had numeric columns
and queries returning (halfway) reliable types.

PR #415 now uses numeric columns in the snippet, too.  That's not
*actually* bullet-proof, as I think vstack will still fail if there's
NULLs coming back from juat a single service (only tried it with the
first dozen servers returned right now).

I could be persuaded that using vstack is a bad idea here in the
first place.  In a realistic setting, the processing should happen
inside the loop, protected by the exception handlers.  If someone has
a creative idea for what that might be, I'll put it in, but it really
shouldn't be more than a line or two...

As to testing, I'm almost entirely sure we don't want to run code
like this as part of some regression/integration suite, mainly because
it will connect random machines, which will simply be too fragile
(and perhaps a bit too expensive) for a reasonable test.  I suppose
there are things for which we will have to rely on users
complaining...

**Comment by bsipocz** [comment]
> As to testing, I'm almost entirely sure we don't want to run code
like this as part of some regression/integration suite, mainly because
it will connect random machines, which will simply be too fragile
(and perhaps a bit too expensive) for a reasonable test.  I suppose
there are things for which we will have to rely on users
complaining

I only run into this while cleaning up the docs for #411. My workaround there was to add an enumerate and break after querying a few e.g. 5 services. I'm certainly not suggesting to run this for all the services, but really just to test that the big picture keeps being executable.
