### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by JannisNe** [astropy/pyvo#430]
When is the next version release planned?
It would be great to have the stability fix in #392 on PyPI to use in other packages!

**Comment by bsipocz** [comment]
I don't think we're ready for a 1.5 just yet, there are a few items that would likely need to wait until after the interop (imo addressing https://github.com/astropy/pyvo/issues/429 would be nice to get into 1.5 if the maintainers agree).

OTOH, we kind of kept milestoning some of the bugfixes as 1.4.1, so branching out, and going through all the PRs systematically and backporting etc could be an interim solution. What do you @tomdonaldson @msdemlei and @andamian think?

**Comment by andamian** [comment]
Nothing against a quick bug fixes 1.4.1 release.

**Comment by msdemlei** [comment]
On Wed, Mar 01, 2023 at 10:32:01AM -0800, Brigitta Sipőcz wrote:
> OTOH, we kind of kept milestoning some of the bugfixes as 1.4.1, so
> branching out, and going through all the PRs systematically and
> backporting etc could be an interim solution. What do you
> @tomdonaldson @msdemlei and @andamian think?

A bugfix release would be charming, but I'll be honest: I don't think
I'll find time for that in the next few weeks.

**Comment by bsipocz** [comment]
That's OK, I'll make the release. But someone needs to add me to pypi as from the 6 who could do a release only 2 are active in the repo.

**Comment by bsipocz** [comment]
Release v1.4.1 is now on pypi.

Note to maintainers: I've turned off squash merging as that feature makes the backport scripts a total nightmare. Pro the backport scripts: I made a huge historical spring clean in the changelog, too.

**Comment by andamian** [comment]
Rogers that! Thanks for the release, @bsipocz
