### ISSUE TITLE
BUG? ErrorSummary not properly parsed?

### ISSUE THREAD

**Issue by agy-why** [astropy/pyvo#431]
Dear PyVO developers,

I am using pyvo: 1.4

I request a job XML file like:
```python
response = tap_service._session.get('{}/async/{}'.format(tap_service._baseurl, job.jobid), stream=True)
```
the latter holds:
```xml
...
<uws:errorSummary>Some Error message\n here comes the details...</uws:errorSummary><uws:results>
...
```

But when I run
```python
>>> job = vo.io.uws.parse_job(response.raw.read)
>>> print(job.errorsummary.__dict__)
{'_config': {'pedantic': None, 'filename': None},
 '_pos': (2, 639),
 '_Element__name': 'errorSummary',
 '_Element__ns': 'uws',
 '_tag_mapping': {},
 '_type': None,
 '_has_detail': None,
 '_message': None}
```

I would have expected something like:

```python
>>> job = vo.io.uws.parse_job(response.raw.read)
>>> print(job.errorsummary.__dict__)
{'_config': {'pedantic': None, 'filename': None},
 '_pos': (2, 639),
 '_Element__name': 'errorSummary',
 '_Element__ns': 'uws',
 '_tag_mapping': {},
 '_type': None,
 '_has_detail': True,
 '_message': 'Some Error message\n here comes the details...'}
```

I am wondering what I am doing wrong. 

I thank you in advance,

Yori

**Comment by msdemlei** [comment]
On Mon, Mar 06, 2023 at 05:28:31AM -0800, agy-why wrote:
> I am wondering what I am doing wrong.

Pretty certainly nothing.  This quacks like a bug, and it walks like
one, too.

Simple check: Take the URI of any failed async job and say

```
pyvo.io.uws.parse_job(uri).to_xml(sys.stdout)
```

-- that'll lose the content of error summary.

Let me look into it.

**Comment by agy-why** [comment]
@msdemlei thank you for your (very) quick response.

**Comment by msdemlei** [comment]
Well, turns out it's never as simple as it seems.  Both io.uws.tree.JobSummary and io.uws.tree.ErrorSummary had a message child, and the way parsing was set up, the message ended directly in the job summary, and was even fetched from there in TAPJob.raise_if_error.

PR #432 rectifies this in the UWS-orthodox way by sticking message into errorsummary (you'll have to say errorsummary.message.content, though).  Please have a look if that's about what you would have expected (and say if you prefer the alternative of having message directly on the job; although I'd say we shouldn't deviate too far from UWS' data model).

And then someone should one day finally properly document all the magic XML parsing hackery we have in pyVO...

**Comment by agy-why** [comment]
Dear @msdemlei I am totally fine with `errorsummary.message.content` as you mention this is the UWS-orthodox way, so let us go for it.

Unfortunately, I am afraid it still does not work for me:
I am using `pyvo: 1.5.dev66+g3cac035`

after pull ing from github: 
```
git fetch origin pull/432/head:fix-uws-errorsummary
git checkout fix-uws-errorsummary
```
The log seems also ok, commit: `3cac03558daedd5c5dd2d343b2f1e881539c77ac`

Then I just `python setup.py install` in my virtualenv and check that pyvo's version is correct by printing: 
```python
>>> print(pyvo.__version__)
1.5.dev66+g3cac035
```

but again: I get `errorsummary.message = None` 

I am further checking if there is something wrong on my side. But it seems that my problem is not solved.

**Comment by agy-why** [comment]
I can confirm that `raise_if_error` works I get the (very nice) `<No useful error from server>`.

**Comment by agy-why** [comment]
I am wondering if I have to provide some more level?
```
...
<uws:errorSummary>
    <uws:content>Some Error message\n here comes the details...</uws:content>
</uws:errorSummary>
...
```

**Comment by msdemlei** [comment]
On Tue, Mar 07, 2023 at 03:50:04AM -0800, agy-why wrote:
> <uws:errorSummary>
>     <uws:content>Some Error message\n here comes the details...</uws:content>
> </uws:errorSummary>

Ah, yes, that's your problem.  That's not UWS-valid.  See:

http://docs.g-vo.org/schemadoc/schemas/UWS_xsd/elements/errorSummary.html

It would have to be

  <uws:errorSummary>
    <uws:message>
      <uws:content>Some Error message\n here comes the details...</uws:content>
    </uws:message>
  </uws:errorSummary>

Hint: If you're writing VO XML documents from scratch, there's now
``stilts xsdvalidate`` that's really helpful to figure out whether
you got it right.  Or, if you're on a Debian system, you can install
gavodachs2-server and run ``dachs adm xsd <file>``.

**Comment by agy-why** [comment]
Thank you for the tips! The plan is to switch to astropy Table.write but we have other priority for now. So I was happy to blindly find a BUG. XD Although problem was on my side. 

thank you again, I wish you a nice day

Yori

**Comment by agy-why** [comment]
It seems that this is not working either.

```xml
<uws:errorSummary>
    <uws:message>
        <uws:content>There has been an server error with your job.</uws:content>
    </uws:message>
</uws:errorSummary>
```

**Comment by msdemlei** [comment]
On Tue, Mar 07, 2023 at 06:07:46AM -0800, agy-why wrote:
> It seems that this is not working either.
>
> ```xml
> <uws:errorSummary>
>     <uws:message>
>         <uws:content>There has been an server error with your job.</uws:content>
>     </uws:message>
> </uws:errorSummary>
> ```

That's because I mixed together the python and the XML view.  The
content thing is an elementtree attribute, sorry.

The real thing is

  <uws:errorSummary>
      <uws:message>Some Error message here comes the
        details...</uws:message>
  </uws:errorSummary>

(and I'm too much in a hurry to make up a proper document to do XSD
validation -- had I done that before, I'd have spared myself this
embarrassment: XSD validation is your friend!)

**Comment by agy-why** [comment]
FYI: this works :D
 ```xml
 <uws:errorSummary>
     <uws:message>
         <uws:content>There has been an server error with your job.</uws:content>
     </uws:message>
 </uws:errorSummary>
 ```
 This does as well:
 ```xml
 <uws:errorSummary>
      <uws:message>Some Error message here comes the details...</uws:message>
  </uws:errorSummary>
  ```
  
  So I guess I'll figure out the real correct one with `XSD validation`, I thank you again. Have a nice day.

**Comment by msdemlei** [comment]
On Wed, Mar 08, 2023 at 01:12:50AM -0800, agy-why wrote:
> FYI: this works :D
>  ```xml
>  <uws:errorSummary>
>      <uws:message>
>          <uws:content>There has been an server error with your job.</uws:content>
>      </uws:message>
>  </uws:errorSummary>

Aw dang.  We really have to do something about our XML parsing magic,
probably beyond properly documenting it.  But then we're not claiming
to be validating, and so as long as we do the right thing with valid
input and not start formatting the hard drive with invalid input (I'm
rather sure we don't) I'd say it's not particularly urgent.

Once people start to only test their implementations against pyVO
(rather than TOPCAT and stilts, say), however, we'll certainly have
to re-visit this.

Until then, I close this bug, ok?
