### ISSUE TITLE
BUG: dev version number on RTD is wrong

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#473]
<img width="203" alt="Screenshot 2023-08-09 at 10 48 33" src="https://github.com/astropy/pyvo/assets/6788290/d25b786e-bf75-4168-8a96-f0cbe35f9d32">

cc @pllim as I think you know the solution to fix this?

**Comment by pllim** [comment]
Is it https://github.com/astropy/astropy/pull/14996 ? It was @saimn's fix, really.

**Comment by bsipocz** [comment]
Hmm, interestingly, this isn't an issue for the PRs, so while I added a fix in #474, I cannot double check that it works as it wasn't broken in the other PRs to begin with 👀 .
