### ISSUE TITLE
DEP: rename and reprecate Table that are not astropy.table.Table

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#477]
I think we should remove/rename all generic usage of `Table` that are not `astropy.table.Table`. 

The one trivial example I found is `vodataservice.Table`, I would suggest to rename the class to `VODataTable` , or something along that line.

A quick scan of the code doesn't reviel other cases, but only in the `__repr__`s, which is dealt with separately in #476

**Comment by msdemlei** [comment]
On Wed, Aug 09, 2023 at 02:06:06PM -0700, Brigitta Sipőcz wrote:
> I think we should remove/rename all generic usage of `Table` that
> are not `astropy.table.Table`.

I think that's a good plan.

> The one trivial example I found is `vodataservice.Table`, I would
> suggest to rename the class to `VODataTable` , or something along
> that line.

...and that's definitely a good case to test that plan.  The trouble
here is that we're mirroring some external nomenclature.  In this
case, that's the <table> element of VODataService, and making the
various classes reflect the names of the underlying elements is, I
think, a fairly important goal, too.

What if we considered "table" something like a reserved word and just
had standard way of defusing it (perhaps with trailing underscores
along the lines of ``class_``and friends, perhaps in some other way)?
Anyway, we should not ad-hoc this case.  I'm sure we will regularly
re-encounter relatives of it.  Consider, for instance, TAPService,
where you have the tables property.  I would like to argue that if we
reserve "table", we should also reserve "tables"...

**Comment by bsipocz** [comment]
>>  The one trivial example I found is `vodataservice.Table`, I would
 suggest to rename the class to `VODataTable` , or something along
 that line.
> ...and that's definitely a good case to test that plan.  The trouble
here is that we're mirroring some external nomenclature.  In this
case, that's the <table> element of VODataService, and making the
various classes reflect the names of the underlying elements is, I
think, a fairly important goal, too.

Do you have a suggestion what would work? `VODataServiceTable` is a bit of a mouthfull (especially if all the rest of the classes are renamed as well, for consistency), but probably best ticks all the boxes above.

> What if we considered "table" something like a reserved word and just
had standard way of defusing it (perhaps with trailing underscores
along the lines of ``class_``and friends, perhaps in some other way)?
Anyway, we should not ad-hoc this case.  I'm sure we will regularly
re-encounter relatives of it.  Consider, for instance, TAPService,
where you have the tables property.  I would like to argue that if we
reserve "table", we should also reserve "tables"...

I think the big difference is that `TapService.table` is not at all confusable with the `astropy.table` module, while importing and using the `Table` class from vodataservice is very much looks like a `Table` all the while their instances have totally different API.

**Comment by msdemlei** [comment]
On Tue, Aug 22, 2023 at 04:30:32PM -0700, Brigitta Sipőcz wrote:
> Do you have a suggestion what would work? `VODataServiceTable` is a
> bit of a mouthfull (especially if all the rest of the classes are
> renamed as well, for consistency), but probably best ticks all the
> boxes above.

I don't think it's visible to non-nerd users, so I wouldn't worry too
much about length.

On the contrary: I'd even consider adding an underscore between the
"disambiguating" prefix and the element name: VODataService_Table, in
hopes that folks may divine why we're deviating from the element name
<-> class name correspondence.

But I'm happy with VODataServiceTable, too.

> I think the big difference is that `TapService.table` is not at all
> confusable with the `astropy.table` module, while importing and
> using the `Table` class from vodataservice is very much looks like
> a `Table` all the while their instances have totally different API.

Ah, ok -- sorry, I hadn't gotten that rationale the first time
around.  That definitely makes a lot of sense, and just avoiding
``Table`` (exactly in that form) in the future ought to be *very*
doable.
