### ISSUE TITLE
BUG: SIA2Service.search() method has separate session

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#487]
`self._session` is set on the class, yet the method has its separate `session` kwarg, defaulting to None. Isn't this a bug?

cc @andamian

**Comment by andamian** [comment]
It looks like it should default to `self._session` otherwise is going to use a new, anon session. I suspect that the problem will become evident (more or less) when the service class is initialized with a A&A session but will issue anon queries.

**Comment by bsipocz** [comment]
OK, I'll open a new PR for the fix then. Run into this while I was fixing https://github.com/astropy/astroquery/pull/2836, where we also defaulted back to a new session rather than passing the one set up from astroquery.
