### ISSUE TITLE
Dependency with XML parser

### ISSUE THREAD

**Issue by somilia** [astropy/pyvo#498]
The code implementing the MIVOT feature (PR #497) uses [lxml.etree](https://pypi.org/project/lxml/). The data model handling requires to run XML operations: parsing and XPATH queries.

However, lxml is not a part of the PyVO dependencies, and is considered insecure as well as the xml native package ([xml documentation](https://docs.python.org/3/library/xml.etree.elementtree.html)), the reason why we have been resilient in using them.

The two possibilities are:
 - use [defusedxml](https://pypi.org/project/defusedxml/) which will also add a new dependency.
 - add the fragment needed of defusedxml in PyVO (defusedxml is on Python Software Foundation License)

What would you recommend?

**Comment by bsipocz** [comment]
Either of them ends up as a dependency they will need to be an optional dependency, e.g imports needs to be done as part of conditionals, test should be skipped when the dependency is missing, etc.
For examples see the case e.g. `regions` in astroquery.
