### ISSUE TITLE
[1.4.2] TestDALResults.test_init fails with Astropy 6.0

### ISSUE THREAD

**Issue by olebole** [astropy/pyvo#499]
With Astropy 6.0, I get the following CI test failure:
```python
___________________________ TestDALResults.test_init ___________________________

self = <pyvo.dal.tests.test_query.TestDALResults object at 0x7f64516e1e10>

    def test_init(self):
        dalresults = DALResults.from_result_url(
            'http://example.com/query/basic')
    
        assert dalresults.queryurl == 'http://example.com/query/basic'
        assert isinstance(dalresults.votable, VOTableFile)
>       assert isinstance(dalresults.resultstable, VOTable)
E       AssertionError: assert False
E        +  where False = isinstance(<VOTable length=3>\n  _1                    _2                 \nint64                 str37                \n----- -----...                    Illuminatus\n   42 Don't panic, and always carry a towel\n 1337                                 Elite, VOTable)
E        +    where <VOTable length=3>\n  _1                    _2                 \nint64                 str37                \n----- -----...                    Illuminatus\n   42 Don't panic, and always carry a towel\n 1337                                 Elite = <Table length=3>\n  1                     2                  \nint64                 str37                \n----- -------...                    Illuminatus\n   42 Don't panic, and always carry a towel\n 1337                                 Elite.resultstable

/usr/lib/python3/dist-packages/pyvo/dal/tests/test_query.py:274: AssertionError
```
[Full build log](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pyvo/40223526/log.gz)

I couldn't find out whether this was fixed after 1.4.2; in this case I would like to have the relevant commit (I'll apply it to the Debian package), or maybe an updated version.

**Comment by pllim** [comment]
The devdeps job is failing for other reasons, so I cannot check there: https://github.com/astropy/pyvo/actions/runs/6986643081

However, devdeps from 2 weeks ago passed with astropy v6.1.dev: https://github.com/astropy/pyvo/actions/runs/6911420835/job/18805926250

**Comment by pllim** [comment]
The regular CI did pass with astropy 6.0.0 (stable) when I restarted it: https://github.com/astropy/pyvo/actions/runs/6986641688/job/19102165572

So, this means the reported failure here is already patched but unreleased.

Hope this helps!

**Comment by olebole** [comment]
Is there a new release planned?

**Comment by tomdonaldson** [comment]
Without looking too carefully, I'm assuming #496 is what's needed.  We'll look into doing a release soon.

**Comment by bsipocz** [comment]
We're getting really close to the finish line of the release (practically happens next Mon/Tue), so in the process of cleaning up fixed issues, I'm closing this now.
