### ISSUE TITLE
scs.query search radius should not be an optional parameter

### ISSUE THREAD

**Issue by msdemlei** [astropy/pyvo#512]
Since 01fd8a3f, the radius argument on dal.scs.search is keyword-only. That will break a lot of code; in particular, signalling the search radius somehow optional is not in line with the SCS protocol itself, which has SR as a mandatory parameter.

So... radius should go in front of the *.  Me (and I think not breaking other people's code is a very good thing and more important than following *all* the rules), I'd say the default could stay.  But since I think this particular default isn't very natural anyway, I'd say we should rather drop the default than make radius optional.

**Comment by bsipocz** [comment]
>  But since I think this particular default isn't very natural anyway, I'd say we should rather drop the default than make radius optional.

Indeed, I went with the simple assumption that anything optional in the signature is in fact optional, and with the desire to remove function calls that are a bunch of numbers and booleans without being explicit. 

But moving back one parameter is totally fine.

**Comment by msdemlei** [comment]
Can I re-open this for sia?  SSAP... not sure, threre is probably not much code around using it.  For SIA2, I think we should keep things as they are; field_of_view is probably a bit more exotic than the size argument in SIA1.
