### ISSUE TITLE
get_service's positional argument is not really optional

### ISSUE THREAD

**Issue by msdemlei** [astropy/pyvo#513]
Since c4c3c6ec, the service_type argument on the get_interface and get_service methods of regtap.RegistryResource is keyword-only.  This breaks a lot of code, in particular the one I've been giving in my pep posts, https://blog.g-vo.org/towards-data-discovery-in-pyvo.html.  It also is conceptually wrong, as people *in general* need to say which service they expect in order to know what kind of interface they will have for what returns.

So... service_type really *must* be a positional argument.  Can we fix this?  Perhaps even in a bugfix release for 1.5?

For compatibility with legacy usage, I'd argue we should still allow not passing the service type, i.e., the default None that probably triggered making this optional.  This still works ok when you have constrained the service type in the discovery query, and disallowing it will again break code, which isn't nice.  My preference would be: We mildly admonish people to start passing in service types now (even when they have constrained the servicetype, which of course they shouldn't be doing either) in the documentation and then see if people change their bad habits.

**Comment by ManonMarchand** [comment]
Oops sorry!!! I thinks this commit was not included in 1.5  so we should be ok without a backport
