### ISSUE TITLE
astropy test dependencies are mandatory for pyvo

### ISSUE THREAD

**Issue by ManonMarchand** [astropy/pyvo#604]
Hi here, 

I was testing the emscripten port of pyvo and it cannot work because a mandatory dependency is missing somewhere.
The failing line is https://github.com/astropy/pyvo/blob/b2f8ca19bd0f54d90ed93fb4c164ba8d3b85a7f0/pyvo/_astropy_init.py#L12 

Which returns a missing module error. Astropy works fine otherwise.

And @pllim pointed here https://github.com/astropy/astropy/issues/16739#issuecomment-2386042775 that it means that pyvo should also declare that it needs astropy testing dependencies.

Do we really need to import `astropy.tests` on every single `import pyvo`?

**Comment by pllim** [comment]
Huh... I guess on CI, your pytest dependency is always there so this is overlooked. 🤔

**Comment by pllim** [comment]
It is in `astropy/__init__.py` too

https://github.com/astropy/astropy/blob/04dfd245ac7815e20908ff7d079f5ad98dd0b2e4/astropy/__init__.py#L137

But even when we build wheels there, we run pytest, so this was never a problem. 😬

**Comment by pllim** [comment]
But wait... `astropy` itself does not have this problem. Imports work without pytest because it is not actually imported very high up. What is your exact traceback? Do you have a very old copy of `astropy`?

**Comment by ManonMarchand** [comment]
The issue is not in `astropy`, it's in `pyvo`. 

This is very high : https://github.com/astropy/pyvo/blob/b2f8ca19bd0f54d90ed93fb4c164ba8d3b85a7f0/pyvo/_astropy_init.py#L12

The traceback is : 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pyvo

File /lib/python3.11/site-packages/pyvo/__init__.py:32
      3 """
      4 PyVO is a package providing access to remote data and services of the
      5 Virtual observatory (VO) using Python.
   (...)
     26 of which DALAccessError is the root parent exception.
     27 """
     29 # Affiliated packages may add whatever they like to this file, but
     30 # should keep this content at the top.
     31 # ----------------------------------------------------------------------------
---> 32 from ._astropy_init import *
     33 # ----------------------------------------------------------------------------
     35 from . import registry

File /lib/python3.11/site-packages/pyvo/_astropy_init.py:12
      9     __version__ = ''
     11 # Create the test function for self test
---> 12 from astropy.tests.runner import TestRunner
     13 test = TestRunner.make_test_runner_in(os.path.dirname(__file__))

ModuleNotFoundError: No module named 'astropy.tests'
```

**Comment by pllim** [comment]
`ModuleNotFoundError: No module named 'astropy.tests'` suggests that your astropy is not installed properly. Try `import astropy; astropy.__version__` -- does that work?

**Comment by ManonMarchand** [comment]
Yup. It's 6.1.4, distributed through emscripten-forge

**Comment by ManonMarchand** [comment]
You can try the install live here https://manonmarchand.github.io/tap-tap-tap/lab/index.html

**Comment by ManonMarchand** [comment]
Then it won't run in the browser if I don't take it from emscripten-forge. There is no `conda` cli in a jupyterlite instance.
PyVO comes from conda forge though, as it is pure python.

**Comment by pllim** [comment]
You might also be interested in:

* https://github.com/conda-forge/astropy-feedstock/pull/137

**Comment by bsipocz** [comment]
For functionality I don't see a way around not requiring astropy, but we can certainly remove the TestRunner dependency here.

@pllim - no, emscripten and conda-forge is not a mix and match, conda and what astropy supports is not relevant here.

Also, 🎉 @ManonMarchand for getting the balls rolling for this, I was looking into pyodide and web interactivity for pyvo, it  earlier this summer but didn't have enough time to explore besides that it seemed to work to the level of importing without issues.

**Comment by pllim** [comment]
If you don't use `pyvo.test()` anywhere, you indeed do not need the test runner. Good luck!
