### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [astropy/pyvo#612]
In https://github.com/astropy/pyvo/blob/8f5e780102295ff4bff137af32ba61da3bc88579/pyvo/dal/query.py#L215 there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if the `try` body raises anything other than `requests.RequestException` (including a `BaseException` such as `KeyboardInterrupt`), it will not propagate on as expected.

Similarly, in 
https://github.com/astropy/pyvo/blob/8f5e780102295ff4bff137af32ba61da3bc88579/pyvo/dal/query.py#L1057
the return would swallow any exception raised in the `try` body.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by bsipocz** [comment]
Thank you for reporting this!
