### ISSUE TITLE
Bug: DALQueryError caused by interpolated `np.float64`

### ISSUE THREAD

**Issue by fjebaker** [astropy/pyvo#623]
This might be a bit of a duplicate of https://github.com/astropy/pyvo/issues/568 or at the very least related.

I was following [Markus's pyvo-course](https://codeberg.org/msdemlei/pyvo-course) and hit a `DALQueryError`. 

Stripping down Markus's code to a MRE:
```py
from pyvo import registry
from astropy.coordinates import SkyCoord

result = registry.search(
    registry.Spatial((SkyCoord.from_name("M42"), 2))
)
```
Output:
```
...
  File "/home/lilith/.local/share/hatch/env/virtual/vo/nmg7WNbb/vo/lib/python3.12/site-packages/pyvo/registry/regtap.py", line 271, in execute
    return RegistryResults(self.execute_votable(), url=self.queryurl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lilith/.local/share/hatch/env/virtual/vo/nmg7WNbb/vo/lib/python3.12/site-packages/pyvo/dal/query.py", line 336, in __init__
    raise DALQueryError(self._status[1], self._status[0], url)
pyvo.dal.exceptions.DALQueryError: Field query: Could not parse your query: Expected ")", found ','  (at char 781), (line:13, col:78)
```
Looking at the query it generates by replacing `search` with `get_RegTAP_query`:
```sql
SELECT
ivoid, res_type, short_name, res_title, content_level, res_description, reference_url, creator_seq, created, updated, rights, content_type, source_format, source_value, region_of_regard, waveband,
  ivo_string_agg(COALESCE(access_url, ''), ':::py VO sep:::') AS access_urls,
  ivo_string_agg(COALESCE(standard_id, ''), ':::py VO sep:::') AS standard_ids,
  ivo_string_agg(COALESCE(intf_type, ''), ':::py VO sep:::') AS intf_types,
  ivo_string_agg(COALESCE(intf_role, ''), ':::py VO sep:::') AS intf_roles,
  ivo_string_agg(COALESCE(cap_description, ''), ':::py VO sep:::') AS cap_descriptions
FROM
rr.resource
NATURAL LEFT OUTER JOIN rr.capability
NATURAL LEFT OUTER JOIN rr.interface
WHERE
(ivoid IN (SELECT DISTINCT ivoid FROM rr.stc_spatial WHERE 1 = CONTAINS(MOC(6, CIRCLE(np.float64(83.8201), np.float64(-5.3876), 2)), coverage)))
GROUP BY
ivoid, res_type, short_name, res_title, content_level, res_description, reference_url, creator_seq, created, updated, rights, content_type, source_format, source_value, region_of_regard, waveband
```

I am brand new to `pyvo` but having `np.float64` looks pretty odd, and I found some related issues (e.g. https://github.com/astropy/pyvo/issues/479). 

My guess is that these lines are the culprit:
https://github.com/astropy/pyvo/blob/99e0fd93b3c388e18cbef55084992c6dd09095c3/pyvo/registry/rtcons.py#L108-L109

But I'm not sure what the preferred approach to fixing this is, since it seems to be something discussed in many repositories.

Posting this just to let you know! Thanks :)

---

```
$ python3 --version
Python 3.12.7
$ pip freeze | grep -e pyvo== -e astropy== -e numpy==
astropy==7.0.0
numpy==2.1.3
pyvo==1.6
```

**Comment by ManonMarchand** [comment]
Looks like the change of repr in numpy > 2.0 broke the query there. Thanks for reporting this!

**Comment by bsipocz** [comment]
Thanks Fergus for the MRE, doing that for any of the lazy issues I open as a copy-paste from a CI traceback is much appreciated! 

And having some loose numpy2.0 repr bugs still around in the code doesn't exactly surprising.

**Comment by bsipocz** [comment]
So, what we actually have here is that we masked an actual regression in #481 by forcing the CI to use the legacy repr. It nicely bit me back, I'm sorry about it.
